- JeongGod/14425.py
- JeongGod/1966.py
저도 코드에다가 알고리즘 풀이를 적었습니다!
다음부터는 여기다가 적겠습니다ㅎㅎ
> 7월 15일 이정규 - BOJ 1966 : 프린터 큐 & BOJ 14425 : 문자열 집합 #3

- JeongGod/14501.py
- JeongGod/2961.py
14501 - 퇴사
n = 15밖에 주어지지 않아서 Brute Force방식으로 충분히 풀 수 있겠다고 생각하고 풀이를 적었다.
<풀이>
1. 1 ~ n일까지 가능한 모든 상담을 계산한다.
2. 상담의 걸리는 시간을 더하여 다음 재귀에서는 그 걸린 시간 이후부터 n일까지 계산한다.
3. 만약 일수가 N일이 넘어간다면 재귀를 종료한다.
2961 - 도영이가 만든 맛있는 음식
<풀이>
1. 조합을 이용해 1~n개를 뽑는 모든 경우의 수를 뽑는다.
2. n개를 선택한 경우의 수중에서 1개를 뽑는다.
3. 값을 계산하여 비교한다.
> [2021.07.19] BOJ 14501, 2961

- notCoderJ/16943.py
- notCoderJ/2422.py
`2422: 한윤정이 이탈리아에 가서 아이스크림을 사먹는데`
- 풀이 과정:
주어진 N의 최댓값이 200이므로 N개에서 3개를 선택하는 조합의 수가 약 130만으로 모든 경우의 수를 탐색해도 괜찮다고 생각했습니다. 그래서 섞지 말아야할 아이스크림 조합에 대한 집합을 만들고, N개 중 3개의 아이스크림을 선택하는 조합을 구해 하나씩 돌며 해당 집합과 교집합이 없는 경우만 카운트하여 아이스크림을 조합수를 구하겠다고 생각했습니다.
`16943: 숫자 재배치`
- 풀이 과정:
주어진 A값의 범위는 크지만 자릿수는 최대 10자리이므로 A에 대한 순열을 구해서 B값과 하나씩 비교하며 B보다 작은 값 중 큰 값을 출력하면 되겠다고 생각했습니다.
1. A값에 중복 값이 있는 경우 순열을 구하면 중복된 값이 나오기 때문에 A의 순열을 구해서 집합으로 만들었습니다.
2. 1번에서 구한 순열을 순회하며 첫 자리가 0으로 시작하지 않고 B값보다 작은 값 중 최댓값을 구했습니다.
> [2021.07.20] 전진성 BOJ 2422, 16943

- JeongGod/16943.py
- JeongGod/2422.py
100개의 아이스크림을 비교하면 된다는 것과, 3개만 선택한다는 것에 대해서 3중포문으로도 충분히 가능하다고 생각했습니다.
`O(n^3)  = > 200^3 = 8,000,000`
조합의 개수는 10000개로 리스트로 찾는다고 한다면 O(n)으로 위에 for문안에서 비교하기에는 
`O(n^3 * m * m)`으로 시간초과가 날 것 같아 집합으로 구현했습니다.
<hr/>
1억의 숫자를 가지고 있다지만 결국 숫자 하나하나를 다루는 것이기에 10개만 다룹니다.
순열은 O(n!)이기에 충분히 가능하다고 생각하여 순열로 작성했습니다.
`permutation`함수를 쓰기 위해서는 iterable한 자료가 들어와야 해서 string형태로 변환 후 다시 int형으로 바꿨습니다.
제가 시간복잡도를 구하는 연습을 하고 있는데 정확하게 맞는지는 모르겠네요..ㅎㅎ 한 번 나중에 검토해주시면 감사하겠습니다!
> [2021.07.20] 이정규 BOJ 2422, 16493

- limhizy15/brute_force/16943.py
- limhizy15/brute_force/2422.py
`16943 - 숫자 재배치`
일단 a를 문자열로 바꾸고 이걸로 가능한 순열을 모두 구했습니다. 
구한 순열을 join으로 다시 문자열로 만들고 생성된 문자열 중
b보다 작으면서 최댓값인 경우를 찾았습니다. 대신 맨 앞에 0이 오는 경우가 올 수 있어 예외처리했습니다.
permutations를 이용했는데 너무 쉽게 풀려서 이게 맞나 싶네요.
`2422 - 한윤정이 이탈리아에 가서 아이스크림을 사먹는데`
쉽다고 생각하고 막 풀다가 시간초과의 늪에서 빠져나오지 못했습니다..
일단 최악의 조합들을 "x&y"형태로 만들어 딕셔너리의 키값으로 사용했습니다.
그리고선 아이스크림 중 3개를 고르고 (combinations)
고른 조합 안에서 또 2개를 고르고 (combinations)
이 2개를 "a&b" 형태로 만들어서 최악의 조합 딕셔너리에 있는지 체크했습니다.
=> 원래 딕셔너리로 안하고 for문을 써서 시간초과가 났었습니다. 진성님께서 집합 사용해보라고 하셔서 코드를 바꿨네요. 근데 set을 안썼네요.. 정신이 없었나봐요
> [2021.07.20] 임희지 BOJ 16943, 2422

- limhizy15/brute_force/1018.py
- limhizy15/brute_force/19699.py
`1018 - 체스판 다시 칠하기`
전체 보드판에서 8*8보드를 완전탐색해서 풀었습니다. 
인덱스를 기준으로 조건문을 작성했고 바꿔칠해야하면 시작 색이 흰인지 검인지 보고 카운팅했습니다. 말로 설명을 못하겠네요.. 코드 한번 봐주세요 😢
처음에 추출한 8*8보드의 시작점이 바뀌면 안된다고 착각했다가,, 삽질 조금했네요
`19699 - 소-난다!`
이 문제는 n개 중에 m개 순열 찾고 몸무게 합을 구한 뒤 배열에 저장했습니다. 그러고 중복 제거해줬어요
소수판별 어떻게할까 하다가 에라토스테네스의 체를 활용했습니다. 앞에서 구한 몸무게 합의 최댓값까지 소수판별을 해서 primes배열에 저장했습니다.
그러고 나서 몸무게 합 배열의 원소가 primes에서 false인지 (소수인지) 체크해서 정답 배열에 넣었어요~
> [2021.07.21] 임희지 BOJ 1018, 19699

- limhizy15/brute_force/14620.py
- limhizy15/brute_force/16508_failed.py
맞는 로직인 줄 알고 구현하던 도중 잘못 생각했다는 걸 알게됐습니다. (그래서 실패코드를 올립니다. 혹시 어떤 점 고치면 될 것 같은지 알 것 같으면 말해주세요ㅠ) 구글에 검색했는데 어떻게 푸는지 도무지 감이 안오더라구요. 그리고 제 원래 설계에서 헤어나오지 못해서 하루이틀 있다가 다시 풀어보려고 합니다.
일단 제가 생각한 풀이 방법은 이렇습니다.
1. {책 제목 : 가격}을 딕셔너리에 저장한다.
2. 책 제목의 단어를 쪼개서 배열에 저장한다. (해당 단어가 존재하는 책 제목을 저장)
- BOOK의 경우
- 'B'와 'A'의 아스키코드 값 차이를 인덱스로 만들고 (idx = 1) 
- books_str[1] = ["BOOK"] 이렇게 되도록 하는 겁니다.
3. 그러고서 우리가 만들고자 하는 문자열 T를 순회하면서 book_str에 해당 알파벳을 가지고 있는 책을 찾고 > 이 책이 얼마인지 찾고 > 가장 작은 값을 찾아서 해당 책 제목을 answer이라는 집합에 넣습니다.
4. 그러고 answer 집합 안의 책 가격들을 모두 합하면 된다고 생각했습니다.
근데 T가 하나의 책 제목에서 모두 나오는 경우를 처리를 못하겠더라구요.. 그래서 접근이 아예 잘못되었다는 생각이 들었습니다. 👶 조금 더 생각해보려고 합니다 ㅎㅎ
꽃길 같은 경우엔 bfs/dfs 문제가 떠올랐습니다. 근데 구현을 못하겠더라구요..,, 혼자 씨름하다가 블로그의 풀이들을 보면서 코드 작성법을 참고했습니다. ㅎㅎ
1. 화단의 모든 좌표 중 3개의 좌표를 선택한다.
2. 3개의 좌표에 씨앗을 심었을 때 꽃이 모두 잘 필 수 있는지 확인한다.
- …
> [2021.07.22] 임희지 - BOJ 16508, 14620

- JeongGod/14620.py
- JeongGod/16508.py
정말.. 멍청한 실수를 했었습니다. 무조건 처음 인덱스부터 시작한다고 생각해서 1시간동안 헤맸네요..
일반적인 재귀방식으로 풀었습니다.. 재귀방식인데 visited변수로 방문했는지, 방문을 안했는지 판단하는 변수를 사용하다보니 새로운 점을 알았는데 밑에 적어두겠습니다!
처음에 접근이 어려웠습니다. 조합으로 접근할까, 재귀로 접근할까 하다가 구현하다보니 많이 더러워지더군요. 
그래서 다 갈아엎고 dict를 구현하는데 같은 키끼리 덧셈이 되는게 있을까 구글링을 하다 Counter라는 것을 알게되었습니다.
1. target counter dict를 생성한다.
2. title에 대한 counter dict를 생성한다.
3. title에 대한 조합을 만든다.
4. title에 대한 조합중에서 `target_dict.keys()`를 하나씩 돌아봅니다.(해당 title에서 뽑을 수 있는지 없는지 판단)
-> `target_dict.keys()`는 target의 하나하나의 알파벳을 뜻합니다.
5. 만약 가능한 조합이라면, 해당 조합의 가격을 더해 최소값이랑 비교합니다.
----
제가 오늘 헤매고, 공부했던 점이 있어서 말씀드릴게요!  
파이썬에서는 특이한 점이 있습니다. 모든 것이 "객체"로 구성되어 있습니다. 
그래서 재귀를 돌릴때 주의할 점이 있습니다. return을 해도 해당 값이 유지되는 경우가 있고, 아닌 경우가 있습니다.
예를 들어드리겠습니다.
```python
def test(li):
li.append(1)
print(li) # output : [1]
def main():
_list = [] …
```
> [2021.07.23] 이정규 BOJ 14602, 16508

- notCoderJ/brute_force/14620.py
- notCoderJ/brute_force/16508.py
풀이 요약:
처음에는 재귀로 시도해보려고 한참을 헤매이다가 저주받을 꽃잎때문에 포기...
다른 관점에서 문제를 파악해야겠다고 생각해서 그림판으로 열심히 색칠공부하다가...
꽃의 중점 간 거리가 3이상이어야 한다는 걸 발견하고 유레카를 외친 후 열심히 조합으로 풀었습니다.
1. 2차원 화단의 모든 좌표를 구한 후 3개의 좌표쌍을 모두 구합니다.
2. 1번에서 구한 좌표쌍에서 각 좌표 간 거리가 3이상인지 확인합니다.
3. 모든 거리가 3이상이라면 해당 좌표들에서 가격을 구한 후 answer와 비교해 작은 값을 answer로 취합니다.
으악 코드 너무 지저분해요...🤣
일단 생각한 로직은 주어지는 전공책들을 1 ~ n개까지 선택하는 조합들을 싹다 구한 후 각 조합의 가격을 합치고 제목들을 합칩니다. 이후 각 제목들과 만들고자하는 문자열의 알파벳이 모두 겹치는 케이스에서만 만들고자하는 문자열의 각 알파벳 수를 충족하는 지 확인하여 저렴한 가격으로 갱신해나가는 코드입니다.
> [2021.07.22] 전진성 BOJ 14620, 16508

- limhizy15/graph_traversal/17129.py
- limhizy15/graph_traversal/21938.py
`21938 - 영상처리`
1. 입력을 받으면서 R,G,B값을 board[i][j//3]에 더해서 저장해줬어요. 한 줄에 3*m개니까 3으로 나눠서 인덱스를 결정했습니다.
2. 그 다음엔 보드를 순회하면서 평균을 내고 임계값 t와 비교해서 0, 1로 이진화를 해주었습니다.
3. 보드 크기만큼 visited배열을 생성해서 준비를 하고,
4. 보드를 순회하면서 값이 1이고 (물체) 아직 방문하지 않은 노드이면 bfs를 호출해 해당 노드와 연결된 모든 곳을 방문하도록 했습니다. bfs는 그냥 정형화된 형태로 구현했습니다.
- 제 코드 보면 dy, dx 나눠서 쓰는거랑 bfs 안에 if문을 2개 나눠서 예외처리를 해주는데 조금 쓸데없어보이겠지만 저는 헷갈려서 일부러 나눠서합니다ㅜㅋㅋ
`17129 - 윌리암슨수액빨이딱따구리가 정보섬에 올라온 이유`
1. 딱따구리 위치를 시작점으로 두고 bfs탐색을 했습니다. 원래는 visited배열 하나로만 하려했는데 헷갈려서 거리 저장용 dist, 방문 여부 확인용 visited배열 2개를 생성했어요.
2. bfs함수 안에서는 위 문제랑 방문여부 체크하는 건 똑같은데 이건 거리 구하는 문제니까 dist값 갱신해주는 부분도 넣었습니다. 
3. 그리고서 탐색하는 중에 3, 4, 5를 만나면 뭐가 됐든 일단 2와 가장 가깝다는 뜻이기 때문에 해당 위치의 거리를 리턴하고 함수를 종료해줬습니다.
=> 3번 같이 한 이유 : 원래는 탐색을 다 돌고 3, 4, 5가 있는 위치까지의 거리를 dist에서 구하고, 최소값을 구했는데요, 메모리 초과가 나더라구요. 그래서 bfs를 끝까지 탐색해서 …
> [2021.07.26 임희지 BOJ 21938, 17129

- limhizy15/graph_traversal/18352.py
- limhizy15/graph_traversal/7576.py
`7576 - 토마토`
처음에 뭐를 시작점으로 해야할지 약간 헤맸네요. 풀이과정은 이렇습니다.
1. 창고에 있는 익은 토마토 (1)을 모두 덱에 넣는다. (다 시작점)
2. bfs탐색을 한다. (상하좌우 네 방향)
=> 0인 곳만 방문하며 이전 토마토 + 1을 해준다. (저는 이렇게 해서 일수를 계산했습니다. 거리 계산하듯이!)
3. 모든 탐색이 끝나면 창고에 익지 않은 토마토 (0)이 있는지 확인하고 없으면 제일 큰 값 - 1을 해준다. (토마토 값이 1부터 시작해서)
`18352 - 특정 거리의 도시 찾기`
1. 입력으로 받은 도로 정보를 인접리스트 graph에 저장
2. visited와 dist 배열을 n만큼 생성
3. bfs탐색
=> graph[node]에 연결되어 있는 곳을 모두 탐색 (방문한 곳 제외)
=> 방문 안한 곳은 덱에 삽입하면서 dist[next] = dist[cur] + 1로 거리를 갱신함
=> 거리가 k이면 answer배열에 삽입
4. answer배열 정렬해서 출력
> [2021.07.27] 임희지 - BOJ 7576, 18352

- notCoderJ/dfs_bfs/change_word.py
- notCoderJ/dfs_bfs/travel_path.py
두 문제 모두 이전에 풀었던 문제였지만 다시 새로 풀어봤습니다. 푼지 약 한달 정도 지났는데 다시 풀어보려니 또 새롭네요
생각보다 시간도 오래걸리고요...
먼저, 처음 주어진 단어들에 target이 없는 경우 변경이 불가능하므로 0을 바로 리턴해주고그외의 경우 dfs를 반복적으로 수행하여 시작 단어와 1글자만 다른 단어들로 계속 변경하며 target문자에 도달할 수 있는 경우 현재 answer와 현재까지 변경한 수(전체 단어 수 - 현재 남은 단어 수)를 비교한 후 작은 값으로 answer를 변경하는 과정을 반복헀습니다. 만약 dfs가 종료된 후에도 answer값이 초기 설정한 무한 값이면 변경할 수 없기 때문에 0을 반환했습니다.
새로 푼 풀이보다 이전 풀이가 더 나은 것 같아보이네요;; 이전 풀이 설명은 기존에 써논게 나은 거 같아서 링크로 대신 하겠습니다.
[이전 코드 풀이](https://github.com/notCoderJ/Algorithm-Study/blob/master/Algorithm_Sites/DFS_BFS/word_conversion.md)
이 문제 풀이도 이전에 써논게 나은거 같아서 링크 걸어두겠습니다~
[여행경로 풀이](https://github.com/notCoderJ/Algorithm-Study/blob/master/Algorithm_Sites/DFS_BFS/travel_route.md)
> [2021.07.28] 전진성 프로그래머스 단어변환, 여행경로

- limhizy15/graph_traversal/pro_43163.py
- limhizy15/graph_traversal/pro_43164.py
[처음 생각]
1. words 수만큼 visited 배열을 만든다.
2. begin을 시작으로 words를 dfs로 탐색한다.
=> words 안에서 아직 방문하지 않았고, 현재단어(cur)과 1개만 다르면 방문한다. answer + 1을 해준다.
=> 만약 cur이 target이 되면 종료한다.
- 결론 : 망함
=> words 안에 target이 없는 경우를 생각하지 못했고, 디버깅하면서 찾지 못했습니다.
=> 그리고 위에 2번에 방문하고 answer + 1을 해주었는데 words를 일단 다 탐색하고 깊이를 계산했어야 맞았을 것 같아요
=> 그리고.. 전역변수를 함수 안에서 참조할 때 global을 쓴다는데 이게 헷갈려서 삽질 엄청했어요
[검색 후 풀이]
1. target이 words 배열에 없으면 0을 리턴 (예외처리)
2. stack을 이용한 DFS탐색
=> 시작점(begin)을 스택에 넣고 스택이 빌 때까지 반복문을 돈다.
=> 만약 스택의 top값이 target이면 정답을 찾은 거니까 리턴한다. (지금까지 구한 거리를)
=> 아닌 경우, words를 순회하면서 현재 단어와 한 글자만 다른지 체크 => count_diff 함수로 판별
=> 해당 글자를 아직 방문하지 않았으면 방문처리해주고 스택에 넣는다.
=> **words를 탐색하는 반복문이 끝나면** answer + 1 (이 때 깊이를 갱신해줘야한다.)
이거는 30분 넘게 생각했는데 풀이 자체가 떠오르지 않아서 구글검색을 했습니다.
1. tickets을 인접리스 형태로 변형한다. => graph = {시작점: [도작1, 도착2...], ...} …
> [2021.07.28] 임희지 프로그래머스 - 단어 변환, 여행경로

- JeongGod/1446.py
- JeongGod/9205.py
주석처리 밑에 진짜 답이 있습니다!
처음엔 예전에 풀었던 회의를 할 수 있는 최대 일 수? 와 비슷한 문제인 것 같아서 dfs로 풀다가 못 풀었습니다.
그래서 dp로도 풀리겠다라는 생각이 있었기에 dp로 결국은 풀었습니다.. dfs 로직은 왜 안되는지 더 고민해보고 알려드리겠습니다!
dp식은 `dp[i] = min(dp[i-1] + 1 , dp[지름길 start index] + 지름길 cost)`입니다.
도로를 1칸씩 가다가, 지름길로 가는게 더 빠르다고 판단되면 해당 값으로 바꾸면서 진행되는 로직입니다.
BFS로 풀었습니다. 구현과 섞여있는 문제라 까다로웠네요.
1. 페스티벌장까지의 거리를 계산합니다.
2. 만약 (맥주의 수)* 50보다 작거나 같다면 갈 수 있는 거리로 끝냅니다.
3. 크다면, 현재 내 입장에서 갈 수 있는 편의점을 다 들려서 맥주의 수를 채우고 방문처리를 합니다.
4. 1번부터 다시 반복합니다.
> [2021.08.02] 이정규 BOJ 1446, 9205

- limhizy15/graph_traversal/1446.py
- limhizy15/graph_traversal/9205.py
`1446 - 지름길`
1. 지금길 정보 (시작, 도착, 거리)를 shortcut 배열에 입력 받는다.
2. 세준이가 원래 도로를 지나면서 걸렸던 거리?를 road배열로 생성해준다.
-> 0, 1, 2, 3, ...., 150, 151,, -> 다음 지점까지 거리가 1이므로
3. 0부터 도착지점d까지 탐색을 시작함 (기준 = node)
-> 지금 시작점이 아니라면 현재 거리 road[node]와 이전 노드 road[node-1] + 1  둘 중 최솟값으로 갱신해준다. 지름길로 인해 바뀐 지점과 인접한 경우를 처리해주는 것
-> shortcut 배열을 탐색해서 현재 지점 node에서 시작하는 지름길이 있는지 찾는다.
--> 존재하면 지름길의 끝 점까지의 거리를 최솟값으로 갱신해준다. 지름길로 가는게 좋은지 안좋은지 판단
4. 이렇게 하면 road배열에 0부터의 최단거리가 담겨있으므로 마지막에 road[d]를 출력
`9205 - 맥주 마시면서 걸어가기`
1. 일단 시작점, n개의 편의점, 도착점의 좌표를 pos배열에 저장한다.
2. 어차피 맥주가 다 떨어지면 편의점에 가서 사먹으면 되므로 a 편의점에서 b 편의점까지 갈 수 있는지를 체크하려고 했다. 
3. for문 2개로 시작점, 도착점을 결정한다. (0부터 n+2까지)
-> i에서 j까지 거리를 구해서 1000이하인 경우 dist[i][j] = 1로 만들어줘서 i to j가 가능함을 표시한다.
4. 이제 모든 노드부터 모든 노드까지 최단 거리를 구한다.
-> 그냥 플로이드 워셜 알고리즘 사용
5. 0부터 도착지점까지의 거리가 INF가 아니라면 어떻게든 도착할 …
> [2021.08.02] 임희지 BOJ 1446, 9205

- notCoderJ/graph/1446.py
- notCoderJ/graph/9205.py
**`1446: 지름길`**
다익스트라나 플로이드 워셜 같은 그래프 알고리즘의 경우 풀이 경험이 극히 제한적이여서 방향성을 못잡는 것 같아 구글의 힘을 빌렸습니다. 다익스트라와 다이나믹 프로그래밍이 섞여있는 알고리즘입니다.
먼저, 주어진 도로 간 정보를 defaultdict를 이용해서 기록해두고
최단 거리를 기록할 dist 테이블을 각 지점의 거리로 초기화합니다.
현재 거리와 이전까지 거리 + 1을 비교하여 현재까지 거리를 최단 경로로 갱신합니다.
현재 경로에 연결된 지름길이 있을 경우 해당 지름길의 도착 지점에서 거리가 지름길을 이용했을 때
이득이라면 해당 도착 지점까지 거리를 지름길 거리 + 현재까지 거리 값으로 갱신해줍니다.
**`9205: 맥주마시면서 걸어가기`**
이상한 곳에서 삽질을 많이 했네요; n의 개수를 잘 못 적었다든지 등등... 코드도 영 아니다 싶은게... 다른 분들 풀이보고 배워야겠습니다. 일단 플로이드 워셜로 풀긴했는데 최단 거리를 구하는게 아니라고 생각해서 가능 여부를 체크하는 방식으로 접근했는데 망한 것 같습니다.😋
먼저, 가능 여부를 확인하는 dist 테이블을 False로 초기화한 후 각 자신의 지점 값을 True로 갱신해줍니다.
그 다음 플로이드 워셜 알고리즘을 사용해서 지점 간 이동이 가능한지 확인하고 가능하다면 dist 테이블의 값을 True로 갱신해주었습니다.
> [2021.08.02] 전진성 BOJ 1446

- limhizy15/graph_traversal/1504.py
- limhizy15/graph_traversal/1717.py
전체적인 흐름은 시작점, v1, v2로부터 도달할 수 있는 노드까지의 모든 최단거리를 구하고 v1 -> v2, v2 -> v1 둘 중 어디를 거치는 게 더 짧은가를 찾았습니다.
1. 입력을 받아서 graph표현을 한다. (인접리스트로 구현했는데 진성님이 알려주신대로 default(dict)를 사용할 수도 있다)
2. 다익스트라 함수를 작성한다. (우선순위 큐를 이용하는 방법) 
3. 시작점, v1, v2를 시작으로 다익스트라 함수를 호출해서 최단거리 배열을 받아 저장한다.
4. 시작점 - v1 - v2 - 도착점과 시작점 - v2 - v1 - 도착점 둘 중 더 작은값을 선택한다.
** 양방향인걸 놓쳐서 단방향으로 풀고 맞왜틀 이러고 있었네요 ㅎㅎ
저희 최소신장트리 배울 때, 사이클 확인하는 법 잠깐 언급됐던 거 기억하실지 모르겠어요. 사이클 확인하는 개념 중 하나가 유니온 파인드 알고리즘이라고 합니다.
원래 4주차에 DP문풀을 하려했는데 1반 코치님께 상담했을 때 차라리 그래프가 낫다, 유니온파인드가 코테에 자주나오니 풀어보는 게 좋을 것 같다고 말씀하셨거든요 그래서 오늘 관련 문제를 골라봤습니다! 근데 구현해본 적이 없어서 관련 개념 찾아보면서 풀었습니다!
1. 부모를 자기 자신으로 갖는 부모 테이블을 생성한다.
2. find함수
-> 종료조건 : 자기자신이 부모일 때 자신을 리턴
-> 아닌 경우 자신의 부모를 또 find함수를 호출해 찾는다.
-> 찾은 루트 노드를 반환해주는 함수
3. union함수
-> 두 입력 a, b의 루트노드를 find함수를 통해 찾아준다.
-> 만약 둘이 루트가 같다면 같은 …
> [2021.08.03] 임희지 BOJ 1504, 1717

- limhizy15/SQL.md
- limhizy15/brute_force/15649.py
- limhizy15/brute_force/15649_recursive.py
이번주 일요일에 코딩테스트가 잡혔는데 SQL도 봐서 벼락치기를 좀 했습니다..^^
- SQL.md파일에 문제, 풀이, 정답이 있습니다. 여기서 제일 앞에 알아둘 것 부분은 참고하시면 좋을 것 같아요
- 그리고 JOIN문 문제도 한 번 쓱 보시면 나중에 도움이 되지 않을까 합니다.
문제
- 1부터 n까지 자연수 중 중복 없이  m개를 고른 수열을 모두 출력해라
풀이
1. itertools의 permutations를 이용해서 풀었습니다.
2. 출력방식이 너무 지저분해서 검색해보니 
```python
for item in comb:
print(' '.join(map(str, item)))
```
-> 이렇게 permutations의 결과값을 출력할 수 있었습니다.
너무 itertools에 의존하는게 아닌가 하고 재귀함수를 이용해서 푸는 방법을 찾아봤습니다.
재귀함수는 현재 어느위치의 값을 결정하는지 알려주는 idx, n, m을 매개변수로 받습니다
- 종료조건 : idx가 m이 되면 수열이 완성된 것이므로 출력하고 리턴한다.
- 모든 숫자를 탐색하면서 아직 선택하지 않은 것이 있다면 선택해주고 idx+1 위치의 값을 결정하기 위해 재귀 호출
- 위의 과정이 끝난 후에 선택된 숫자를 선택되지 않음으로 변경해준다
이런 형태의 재귀함수 쓸 일이 많은 것 같은데 아직 손에 익지를 않네요,, 😂
> [2021.08.05] 임희지 프로그래머스 SQL / BOJ 15649

- notCoderJ/brute_force/backtracking/15649.py
- notCoderJ/dfs_bfs/1261.py
- notCoderJ/dfs_bfs/13549.py
- notCoderJ/graph/1504.py
- notCoderJ/two_pointers/11659.py
- notCoderJ/two_pointers/2470.py
죄송해요 너무 늦었네요 한문제 더 풀고 올리려했는데 졸려서 제정신이 아니네요 맑은 정신으로 내일 풀어서 올리겠습니다.
오늘은 투 포인터 알고리즘에 대해 공부해봤습니다.
<u>1차원 배열에서 2개의 포인터를 조작</u>해 원하는 것을 얻는 기법.
N개의 원소가 있는 1차원 배열에서 완전 탐색 시 O(N²)의 시간 복잡도가 걸릴 수 있는 배열의 원소 선택 문제를 O(N)의 시간 복잡도로 해결할 수 있습니다. 문제를 풀다보니 두 포인터의  이동 조건을 정하는 것이 중요한 것 같다고 생각됩니다.
주어진 용액을 오름차 정렬한 후 양 끝단에 포인터를 두어 두 용액을 섞기 시작합니다.
두 용액의 합에 따라 다음 중 하나를 수행합니다.
1. 두 용액의 합이 양수: 우측 인덱스를 1 감소
2. 두 용액의 합이 음수: 좌측 인덱스를 1 즐가
위와 같이 하는 이유는 이미 정렬된 상태의 값들에서 양측의 합이 양수라는 것은 양의 값이 더 크다는 것이고
좌측 인덱스를 증가시키면 양의 값이 더 증가하므로 양의 인덱스를 감소시켜 합의 차이를 줄여나가서 0으로 수렴하기 위함입니다. 음수인 경우 역시 위와 반대로 생각하면 됩니다.
위 과정을 수행하며 현재 혼합물의 절대값이 기존 혼합물의 최소값보다 작으면 혼합물의 용액들로 기존 값을 갱신해줍니다.
먼저 각 인덱스까지의 합을 구한 리스트(sums)를 하나 생성합니다.
i ~ j번째까지 수의 합을 SUM(i, j)라하면 SUM(i, j) = SUM(1, j) - SUM(1, i - 1)이 성립합니다.
따라서, 주어진 (i, j) 값들을 순회하며 sums[j] - sums[i - 1] 값을 …
> [2021.08.06] 전진성 BOJ 2470, 11659

- JeongGod/BinarySearch/10815.py
- JeongGod/BinarySearch/16564.py
이분 탐색에 사로잡혀서 집합으로도 풀 수 있는걸 풀고나서 알았네요.
이분탐색의 기본으로 풀어봤습니다!
일단 풀기는 풀어봤지만 이분탐색 태그가 걸려있어서 어떻게 이게 이분탐색인지 많이 의아했습니다.
그래서 맞은 사람의 풀이를 보던 중 이분탐색과 걸맞는 풀이가 있어서 가져왔습니다. 출처는 pypy3로 푸신 "hmmamado12"분의 풀이입니다.
코드에 주석이 없어서 뜯어보느라 힘들었네요.
<제 풀이>
1. 우선 캐릭터들을 정렬합니다.
2. 정렬된 캐릭터들 중 오른쪽으로 인접해있는 캐릭터들의 차이를 구합니다.
3. 그 차이가 현재 올릴 수 있는 레벨보다 작다면 올릴 수 있는 것으로 판단하고 그 값만큼 레벨을 올립니다.
4. 만약 그 차이를 극복할 수 없다면 나머지 캐릭터들을 최대로 올립니다.
<백준 사람 풀이>
1. 제일 레벨이 작은 캐릭터와 그 캐릭터를 최대로 올릴 수 있는 값을 start, end로 지정합니다.
2. 이분탐색을 통해서 답을 찾습니다.
<이분탐색 과정>
**tmp_K == mid입니다.**
`mid`는 현재 답을 찾기 위한 임시값입니다.
total함수에서 `tmp_k`은 list에서 `mid`값보다 작다면 `mid - xi`를 더합니다. => 그 값은 곧 `답이 mid일 경우 K`가 됩니다.
mid보다 큰 값이 나온다면, 더 볼 가치가 없습니다. `mid`가 답일 경우를 가정했기 때문입니다.
그렇게 `tmp_K(답이 mid일 경우의 K)`값을 리턴하고, 그 값을 `입력받은 K`와 비교합니다.
`tmp_K`가 작다면 진짜 답은 `mid`보다 크거나 같다는 얘기입니다. 그래서 `start = …
> [2021.08.09] 이정규 BOJ 10815, 16564

- limhizy15/two_pointer/10815.py
- limhizy15/two_pointer/16564.py
탐색 시작점이랑 끝점 설정이 정말 어려운 것 같습니다.. 문제를 잘 이해못해서 좀 헤맸네요 ㅎㅎ
1. 일단 시작점은 현재 캐릭터 중 최소레벨, 끝점은 올릴 수 있는 최대 레벨(현재 최대레벨 + k)로 
2. 시작점 <= 끝점일 때까지 반복문
-> 중간값을 구해서 해당 레벨을 달성하기 위해 필요한 레벨 총합 (total)을 구한다
-> total이 k보다 큰 경우는 불가능 & 큰 경우에는 끝점의 위치를 mid - 1로 옮긴다
-> 그 밖으 경우 일단 answer을 현재 중간값으로 해주고 시작점을 mid + 1로 옮긴다
이 문제는 평범했던 것 같습니다!
1. 시작점 끝점을 0과 상근이가 가진 카드 개수 -1로 정한다
2. 중간점에서의 숫자카드 값이 target과 같다면 찾은 것이므로 1을 리턴
3. 만약 target이 더 크면 시작점을 중간점 + 1로, 반대면 끝점을 중간점 - 1로
4. 반복문이 끝났는데 못찾았으면 0을 리턴해준다
=> 찾고자하는 모든 숫자에 대해 1~3을 수행
좀 급하게 올리느라 주석에 제가 문제풀면서 달았던게 그대로 올라갔네요.. 민망!
> [2021.08.09] 임희지 BOJ 16564, 10815

- limhizy15/data_structure/pro_42578.py
- limhizy15/data_structure/pro_42579.py
`생각`
- 손으로 써보다가 그냥.. 평범하게 조합의 개수 구하는 것 같았어요. 모자, 상의, 하의 이렇게 있으면 중학교 때 배운 것 같은데 용어를 모르겠네요 😂 (모자개수 + 1) * (상의개수 + 1) * (하의개수 + 1) - 1 이 공식.. 마지막에 1을 빼는 것은 모두 안입을 때를 제외하기 위함이구요! 
`풀이`
- 딕셔너리를 이용해서 {옷 종류: [아이템이름, 아이템이름 ..]} 이런 식으로 만들어 준다
- 딕셔너리를 순회하면서 옷 종류에 들어있는 (개수 + 1)를 곱하고 마지막에 1을 빼준다
`생각`
- 일단 장르에 속한 노래들의 재생 횟수로 장르를 정렬하고, 장르 내에서 재생 횟수로 곡을 정렬하고 2개씩 뽑으면 되겠다고 생각했습니다. 그래서 그렇게 했어요..ㅎㅎ
- 람다식 이번에 엘리스에서 데이터분석 초입에 가르쳐줘가지고 좀 써봤는데 짱편하네요 
`풀이`
- 딕셔너리를 이용해서 {장르: {노래 번호: 재생횟수, 노래 번호: 재생횟수 ..}, ..} 형태로 만들어준다.
- 재생횟수로 정렬한다. 이 때 key에 람다로 재생횟수 총합을 기준으로!
- 정렬한 딕셔너리를 for문으로 순회하면서 이번엔 재생횟수를 기준으로 노래 번호를 정렬
- 만약 장르 안에 노래 개수가 1 이상이면 1,2번째를 앨범에 추가, 아니면 1번째 것만 추가
> [2021.09.06] 임희지 프로그래머스 - 위장, 베스트 앨범

- notCoderJ/hash/best_album.py
- notCoderJ/hash/camouflage.py
예전에 풀다가 1번에서 계속 시간초과가 나서 멈췄던 문제였습니다. 다시 시도해도 같은 짓을 반복하고 있었네요...
구글님의 힌트를 좀 얻어 선택하지 않는 경우를 추가해서 경우의 수를 구하는 방법을 깨닫고 통과할 수 있었습니다ㅎㅎ
풀이
1. 주어진 옷을 종류에 따라 갯수를 카운팅합니다.
2. 각 갯수에 1을 더한 후(선택하지 않는 조건) 모든 종류의 갯수를 곱해주고 모두 선택하지 않는 경우인 1을 빼줍니다.
뭔가 해놓고 보니 암호같네요;; 풀어서 적겠습니다.
`reduce(lambda x, y: x * y, map(lambda x: x + 1, types.values())) - 1`
이부분은 먼저 map으로 종류별로 카운팅한 갯수에 + 1을 한 값을 만들어준 다음 reduce를 이용해서 각각의 갯수를 곱한겁니다.
장르별로 2개씩 곡을 선정하는 건데 장르에 포함되는 곡이 한개면 추가하고 아닌경우 짝수개만 추가하는 것으로 해석을 해서 이상한 곳에서 계속 삽질하고 있었습니다😅
풀이
1. 각 장르별로 전체 플레이 수와 (각 음악의 플레이 수, 고유번호의 음수 값)를 리스트 형태로 저장합니다.
2. 장르를 전체 플레이 수 기준으로 내림차 정렬한 후 각 장르에서 음악 리스트들을 다시 내림차 정렬합니다.
3. 장르별로 우선순위가 높은 2개의 음악을 선택해 answer에 저장해줍니다.
> [2021.09.06] 전진성 프로그래머스 위장(Lv2), 베스트앨범(Lv3)

- JeongGod/programmers/stack&queue/bridge.py
- JeongGod/programmers/stack&queue/printer.py
저번에 뭔가 풀었던 기억이 있네요. 엘리스에서 풀었었나.. 
기억나는 문제라 바로 감이 잡혀서 쉽게 풀었네요
<풀이>
1. (index, 우선순위)로 queue를 만듭니다.
2. 우선순위를 파악하기 위해 우선순위 배열을 만들어둡니다.
3. 만들어둔 우선순위 배열을 이용해 우선순위를 비교합니다.
4. 우선순위보다 작다면 다시 뒤로, 크거나 같다면 인쇄합니다.
<풀이>
1. 현재 다리에 있는 트럭을 queue로 만듭니다.
2. (현재 다리에 있는 트럭의 무게 + 들어갈 트럭의 무게) <= 버틸 수 있는 다리의 무게라면 추가합니다.
3. (그 트럭이 나와야 할 시간, 트럭의 무게)로 다리 queue에 추가합니다.
4. 트럭이 나와야 할 시간이라면, 현재 다리에서 빼고, 현재 다리에 있는 무게에서 해당 트럭의 무게를 빼줍니다.
> [2021.09.07] 이정규 Programmers 프린터, 다리를 지나는 트럭

- notCoderJ/data_structure/printerQ.js
- notCoderJ/data_structure/printerQ.py
- notCoderJ/data_structure/truck.py
- notCoderJ/hash/best_album.js
- notCoderJ/hash/camouflage.js
로직은 파이썬과 동일합니다.
궁금하신점 있으시면 알려주세요~
이것도 로직은 파이썬과 동일합니다.
하지만 코드가 참 그래서... 코드에 주석으로 설명을 달아놨습니다~
이것도 궁금하신점 있으시면 말씀해주세요~
풀이요약
프로그래머스에서는 풀지 않았는데, 저번 스터디 때 백준에서 풀었던 기억이 어렴풋이 나네요.
풀이를 생각해보다가 아마 정규님 풀이였나요? 매번 가장 높은 우선 순위의 작업을 계산하지 않고
처음에 정렬해놓고 비교하는 방식이 생각나서 그 방식으로 풀어봤습니다.
1. 작업 순서를 내림차 정렬하여 deque에 저장합니다.
2. 알기 원하는 작업을 표시하여 주어진 작업을 순서대로 deque에 저장합니다.
3. 2번의 deque에서 하나씩 꺼내 1번 deque의 0번째 원소, 즉 가장 우선순위가 높은 작업과 일치하는지 확인합니다.
3-1. 일치한다면 answer값을 1 증가시키고 현재 작업이 marking된 작업인지 확인하여 맞다면 answer값을 반환합니다.
3-2. 일치하지 않는다면 다시 2번 deque의 맨 뒤에 넣고 3번 과정을 반복합니다.
자바스크립트 버전은 로직은 비슷해서 코드 내에 간략히 설명 남겼습니다.
코드 아래쪽에 주석으로 된 부분이 원래 제가 풀이하던 코드인데요. 계속 몇개의 테스트에서 실패가 나는데 원인을 못찾고 있어서
구글의 도움을 받아 다른 풀이 방법으로 풀어서 올렸습니다.  해당 주석 부분을 다시 알아보고 수정해서 올려보도록 하겠습니다.
이 문제는 아직 자바스크립트 버전으로는 풀지 않았고 이것도 추가해보겠습니다.
풀이요약
1. 다리 길이만큼 0으로 채워진 다리와 트럭 대기열을 …
> [2021.09.06] 전진성 프로그래머스 위장(Lv2), 베스트 앨범(Lv3) 자바스크립트 버전입니다.

- notCoderJ/data_structure/truck.js
- notCoderJ/kakao/menu_renewal.py
- notCoderJ/sort/biggest_num.py
풀이요약
나름 방향을 잘 잡았다고 생각했으나, 94, 9 이런 경우에 대해 정렬을 어떻게 할지 한참 고민했습니다.  
결국 자릿수를 모두 채워서 비교할 생각을 하고 구현 후 테스트를 했는데 계속 마지막 한개가 통과가 되지않아 질문게시판을 뒤져봤습니다. 0, 0, 0, 0 같이 모두 0이 들어올 경우 '0'이 출력되야 하는데, '0000'이 출력되서 실패하고 있었네요;;
주어진 숫자를 문자로 변환하여 문자를 기준으로 정렬하여 풀이했습니다.
1. 주어진 숫자를 단순히 문자로 변환해서 정렬하면 94, 99, 9 이런 숫자가 들어올 경우 99, 94, 9 이렇게 정렬이 되는데
가장 큰수는 99 9 94와 같은 순서이므로 모든 숫자에 대해 자릿수를 동일하게 맞춰 문자열로 변환 후 정렬해줍니다.
2. 정렬한 수에서 원래 자릿 수만큼의 문자열 형태 숫자를 빼와서 합치고 int로 변환 후 다시 문자열로 변환해서 반환해줍니다.
int로 한번 변환했다가 str로 다시 변환하는 이유는 0, 0, 0, 0 같은 경우 '0'으로 정상 반환하도록 하기 위함입니다.
처음에 각 주문별로 조합을 만들어서 딕셔너리에 넣고 최대 선택 요리 조합을 구할까하다가 총 주문 갯수에서 2 ~ 주문갯수만큼 선택해서 각 주문의 교집합을 구하는 게 더 괜찮겠다 생각하여 이방법으로 계속 시도했습니다. 그런데 예시는 몇개 추가해서도 통과가 되는데 테스트 케이스에서 거의다 런타임에러 판정이 나서 결국 포기하고 처음 생각한 풀이 방법으로 풀었습니다...
풀이요약
모든 주문에 대해서 주어진 코스의 조합 갯수별로 요리 조합을 모두 구하여 각 요리 조합을 선택한 사람 …
> [2021.09.09] 전진성 프로그래머스 가장 큰 수(lv2)

- limhizy15/sort/pro_42746.py
- limhizy15/string/pro_72411.py
`생각`
- 처음엔 그냥 조합만들고 최댓값 비교했는데 시간초과가 걸렸습니다. 당연하겠지만요..
- 그럼 어떻게 해야 시간초과를 피할 수 있을까 고민했고 아예 정렬을 빡세게 하기로 했습니다. 만약 [1, 20, 3] 문자 배열이 있고 1, 20를 비교하는 상황이라면 120과 201을 비교하게했습니다. 이런 식으로 쭉쭉 정렬을 하면 합쳤을 때 가장 큰 수가 나오게 됩니다.
`풀이`
- 일단 numbers들을 모두 문자로 바꿔주었습니다.
- 그 후, 제가 따로 만든 compare함수로 정렬했습니다. (compare함수는 위에 말한 로직으로 구현했습니다.)
- 마지막으로 정렬한 배열을 join으로 문자열로 만들고 다시 int -> str로 변환하는 과정을 거쳤어요. 이 부분 때문에 마지막 테케에서 계속 걸렸었는데 '0000'이면 이게 0으로 바뀌지 않아서 틀리더라구요
`팁..?`
- 제가 정렬을 커스텀해서 쓰려고 하니 C++처럼 간단하지가 않더라구요.. 그래서 파이썬에서는 어떻게 compare함수를 만드는지 검색해서 해결했습니다.
- python2에서는 sorted에 cmp 속성으로 해줄 수 있지만 python3에서는 `cmp_to_key`라는 메서드를 사용합니다. `from functools import cmp_to_key` 이렇게 import할 수 있습니다.
```python
arr2 = sorted(arr, key=cmp_to_key(compare), reverse=True)
```
- 이런식으로 key=cmp_to_key(비교함수 이름)을 넣어주면 됩니다.
<br />
- 처음에 문제 자체를 못알아듣겠어서 …
> [2021.09.09] 임희지 programmers 가장 큰 수, 메뉴 리뉴얼

- JeongGod/programmers/kakao/search_rank.py
너무너무 생각이 안나서 질문게시판 좀 찾아가면서 했습니다. 질문게시판에 해당 로직을 올려주신 분이 있더라구요. 그거대로 구현해봤습니다.
<풀이>
1. info에서 모든 경우의 수를 구한 뒤, key로 삼고 해당 score를 list로 추가합니다.
2. 그 뒤에, query문을 돌면서 해당 query문에 맞는 key값을 찾습니다.
지금 보니, 예외 처리를 하지 않았는데도 되네요. 테케가 무조건 1명 이상이라 런타임 에러가 안 뜬 것 같습니다.
=> defaultdict를 썻기 때문에 되는거였습니다ㅎㅎ 너무 정신없이 풀다보니 놓쳤네요.
3. 찾은 value(score_list)중에서 현재 요구하는 score보다 높은 것의 개수를 찾습니다.
4. 리스트에 추가해줍니다.
음.. 구현은 역시 어렵네요. 더 연습을 해야할 부분인 것 같아요ㅠㅠ 지금 보니 로직은 간단한데, 해당 로직을 생각하기가 힘든 것 같아요ㅠㅠ
이분탐색부분을 빼도 되지 않을까 싶었는데 이분탐색을 빼면 통과 못하더라구요. 이게 왜 레벨 2..
> [2021.09.11] 이정규 Programmers 순위 검색

- notCoderJ/greedy/camera.py
- notCoderJ/kakao/compression.py
기존에 몇번 풀었던 문제여서 생각보다 쉽게 풀긴했는데, 여러 각도에서 바꿔가며 생각해보니 어질어질하네요.
이전에 풀이 후 그림으로 설명해논 것이 있어서 첨부해봅니다. 
[단속카메라](https://github.com/notCoderJ/Algorithm-Study/blob/master/Algorithm_Sites/Greedy/enforcement_camera.md)
풀이 요약
차량들을 나간 지점을 기준으로 정렬한 뒤 현재 차량의 나간 지점과 이전 차량의 진입 지점을 비교하여
현재 차량의 나간 지점 < 이전 차량의 진입 지점이면 현재 차량의 진입 지점에 카메라를 1대 추가하고 카메라의 설치 위치를 갱신합니다.
현재 차량의 나간 지점 > 이전 차량의 진입 지점인 경우 이전 차량의 진입 지점과 현재 차량의 진입 지점을 비교하여 더 큰 값으로 카메라의 위치를 갱신해줍니다.
실제 풀이는 위 로직을 사용했으나 정렬만 역순으로 하여 진행했습니다.
예를 들어 현재 차량 = (5, 7), 이전 차량 = (3, 9)라면
현재 차량의 나간 지점(7) > 이전 차량의 진입 지점(5)이므로
카메라를 추가하지 않고 카메라의 설치 위치만 둘의 진입 지점 중 더 큰 값(5)로 갱신합니다.
단순히 문제에서 주어진대로 변환을 하면서 사전에 등록하는 방식으로 풀었습니다.
풀이 요약
1. string의 영문 대문자 문자열을 가져와서 초기 길이가 1인 사전을 만들어줍니다.
2. 주어진 문자열을 하나씩 돌며, 현재 문자를 이어붙이고 사전에 있는지 확인합니다.
3. 만약 사전에 현재 이어붙인 문자열이 존재하지 않으면
해당 문자열의 끝문자를 제외한 …
> [2021.09.13] 전진성 프로그래머스 단속카메라(lv3), 2018 카카오 블라인드 압축

- limhizy15/greedy/pro_42884.py
- limhizy15/implementation/pro_17684.py
**어려웠던 점**
- 그리디 문제였기때문에 손으로 그리면서 어떤 게 최선의 선택인지 고민을 많이했어요. 근데 분명 테케도 되고 제가 만든 테케도 되는데 왜 안되지? 이러면서 답답했네요.. 근데 이게 문제가 한 번 이게 최선의 선택이다! 라는게 머릿속에 박히니까 다른 쪽으로는 생각을 못하겠더라구요.. 다른 분 풀이 검색하면서 약간 허무했습니다ㅋㅋ
**풀이**
1. routes 배열을 차량이 나가는 지점을 기준으로 정렬합니다. (저는 처음에 이동경로가 가장 작은 것과 차량이 나가는 지점 두 개로 정렬을 했는데 그럴 필요가 없었어요..)
2. routes의 제일 앞의 차량이 나가는 지점에 카메라를 설치합니다. 
3. 그런 뒤 새로운 카메라를 설치했을 때 검사가 되는 애들을 체크해줍니다. 전 이 부분은 visited 배열을 만들어서 체크했습니다!
4. 2, 3번을 반복하며 카메라를 설치하면 끝!
**어려웠던 점**
- 마지막 부분 예외처리하는 게 어려웠어요. 그냥 문제에 나온 그대로 코딩하면 되는 거였는데 마지막에 이제 c가 ''일 때 처리를 잘 못해서 오래 걸렸습니다..
- 😎 해결 : 그냥 로직 밖에서 마지막 것 처리해주기..
**풀이**
1. 문제대로 사전을 초기화해줍니다. 아스키코드를 활용하기 위해서 chr함수를 활용했습니다.
2. msg를 돌면서 target에 한 문자씩 더해주고 target이 사전에 없는 경우 마지막 문자를 뺀 후, 사전에서 색인 번호를 추출합니다.
3. target이 w+c이기 때문에 target을 새로운 색인 번호와 함께 딕셔너리에 추가했어요
4. 그리고 마지막 부분은 while문 …
> [2021.09.13] 임희지 programmers 단속카메라, 압축

- JeongGod/programmers/greedy/camera.py
- JeongGod/programmers/kakao/compression.py
풀이가 떠오르지 않아서 좀 찾아봤네요. 그리디쪽은 아직 많이 안풀어봐서 감이 안잡히네요ㅠㅠ
<풀이>
1. 우선 routes를 sort합니다. 진입 시점은 오름차순, 진출 시점은 내림차순으로 정렬합니다.
**=> 처음에는 진출 시점도 내림차순으로 했지만 (#진입 시점을 확인한다) 이 부분에서 어차피 걸러지네요. 그래서 뺐습니다.** 
2. 첫번째로 들어온 차의 진출 지점을 카메라의 위치로 잡습니다.
3. 그 다음차의 진출 시점을 확인합니다.
1. 그 차의 진출 시점 <= 카메라의 위치
최적의 카메라 위치입니다. 변경하고 2번으로 돌아갑니다.
2. 크다면
진입시점을 확인합니다. 
1. 그 차의 진입 시점 <= 카메라의 위치
현재 카메라의 위치로 그 차를 찍을 수 있습니다. 2번으로 돌아갑니다.
2. 크다면
카메라를 새로 설치해야 하므로 위치를 새로 잡은 뒤 카메라의 개수를 +1합니다.
코테보면 구현하는 문제가 참 많은 것 같아요. 많이 연습해야할 것 같아요 후..
<풀이>
1. 현재 문자를 첫 문자로 잡습니다.
2. 현재 문자 + 다음 문자가 dict에 있는지 봅니다.
3. 있다면 1번으로 돌아갑니다.
4. 없다면 현재까지 구한 최장 문자열의 색인번호를 저장합니다.
5. 그 뒤에, 새로운 문자열일테니 dict에 추가합니다.
6. msg에서 지금까지 구한 최장 문자열을 제거한 뒤, 1번으로 돌아갑니다.
> [2021.09.13] 이정규 Programmers 단속카메라, 압축

- JYP/Programmers_test_kit/camera.py
- JYP/kakao_blind/2021_compression.py
* 오늘 컨디션이 너무 안좋아서 일찍 자야될 것 같아서 풀이는 대부분 검색을 미리 하고 봤습니다.ㅠ 
`로직`
- 검색해서 찾은 로직을 그대로 썼습니다🥲🙏
- [진입, 진출]로 데이터가 들어오니 진출점을 기준으로 데이터를 우선 정렬합니다.
- 처음에는 기본 카메라 1대가 있어야 합니다.
- 다음 진입점이 이전 진출점보다 클 경우, 즉 차의 이동 구간이 서로 겹치지 않는 경우 단속카메라를 한 대 더 추가합니다. 
`추가 정리 링크`
- https://freckle-alarm-005.notion.site/3-f3cbb5ba83fa40b1b226a6c386862333
`로직`
- 1. 알파벳: 키 쌍으로 초기화 - defaultdict 사용
- 2. LZW 구현
- 문자열에서 탐색할 start, end 포인트를 잡아두었습니다. 
- 시작과 끝 구간의 문자열을 갖는 w보다 항상 한 칸 더 앞을 탐색하는 c도 같이 둡니다. 
(제 코드에서는 c가 문제 설명의 w+c의 역할을 하게됩니다.)
- c값이 테이블에 없다면 w값을 출력하고, c를 사전에 추가합니다. 마지막 차례라면 마지막 원소 1개만을 출력합니다.
- c값이 테이블에 있다면 마지막 차례인지만 검사합니다.
`알게된 점`
- 생전 처음 보는 LZW알고리즘을 알게되었네요 ㅎㅎ
- string.ascii_uppercase는 자주 안써서 이럴 때 써버릇해야 안 까먹게 되는 거 같네요🥲
- 성격이 급해서 문제를 덜 읽고 또 풀뻔했네요; 처음에 아스키코드를 다 입력해야 하는 줄 알고 ord() 함수를 찾아봤는데 결국 안썼습니다.
`추가 정리 링크`
- …
> [2021.09.13] 박지윤 | 프로그래머스: 단속카메라 / 카카오 블라인드: 압축

- JYP/Programmers_test_kit/h_index.py
- JYP/Programmers_test_kit/is_prime.py
- JYP/kakao_blind/2020_string_compression.py
`로직`
- 첫번째 for문은 문자열을 슬라이싱할 단위(step)의 크기를 1씩 증가시키는 구문입니다.
- while문은 슬라이싱할 위치 j가 문자열의 크기를 넘지 않는 동안 작업을 진행하는 구문입니다.
- curr : 현재위치에서 step size(i)만큼 슬라이싱한 문자열 조각입니다.
- next : 그 다음위치에서 setp size(i)만큼 슬라이싱한 문자열 조각입니다.
- 현재 조각과 다음 조각이 일치하면 일단 카운트 수를 늘려줍니다.
- 현재와 다음이 다를 경우,
- 다음 조각이 있다면,
- 카운트가 1 이상인 경우: 지금까지 카운트한 문자열의 수cnt와 현재 문자열 curr을 answer에 붙입니다. 예 : 2 + ab = 2ab(string)
- 카운트가 1인 경우: 이전과 현재 조각이 다른 문자열이었다는 의미이므로 카운트 숫자를 제외하고 curr만 answer에 덧붙입니다.
- 다음 조각이 없다면(하지만 남은 문자열은 있을 수 있음 - 애매한 김밥 꼬다리 같은 느낌?)
- 카운트가 1 이상인 경우 : 카운트한 문자열의 수와 현재의 조각과 나머지 전체를 합친 s[j:]를 answer에 덧붙입니다.
- 카운트가 1인 경우 : 카운트 수를 빼고 현재부터 마지막까지 남은 문자열 s[j:]을 모두 answer에 붙입니다.
- while문을 다 돌고 나면 result배열에 answer 문자열의 길이를 추가해줍니다.
- 마지막으로 result의 최솟값을 반환합니다.
** 수정을 두차례 했는데 로직 설명은 최종 업데이트 기준으로 작성했습니다!
`로직`
- 우선 인용횟수를 담은 배열을 오름차순으로 정렬합니다. …
> [2020.09.15] 박지윤 - 카카오: 문자열 압축, 프로그래머스: H Index

- JeongGod/programmers/binary_search/h-index.py
- JeongGod/programmers/kakao/str_compression.py
범위가 작아서 전체를 흝는것도 가능해보였지만 이분탐색을 좀 섞었습니다.
<풀이>
1. 1부터 10000까지 가능한 작은 h부터 하나씩 넣어봅니다.
2. h의 위치를 bisect_left로 찾습니다. 전체 길이에서 해당 index번호를 빼 길이를 구합니다.
3. 그 길이가 h보다 크거나 같다면 가능한 h이므로 교체해줍니다.
다른 사람의 풀이를 보다가 enumerate사용과 그냥 푸는 방식이 아름다워서 가지고 와봤습니다.
이해하는데 많은 시간이 걸렸는데 설명해드리겠습니다.
1. 역순으로 정렬합니다.
2. enumerate를 이용하여 (val, idx)꼴로 만듭니다. 여기서 idx는 citations에서 val보다 크거나 같은 "길이"를 뜻합니다.
3. enumerate에서 (val, idx) 중에서 작은 친구를 고릅니다. 바로 h의 후보를 뽑는 일입니다.
=> 이 부분이 저도 이해가 조금 힘들어서.. 뭔가 느낌은 오는데 설명이 힘드네요..
4. h의 후보중에서 최댓값을 뽑습니다.
<풀이>
1. 1~len(s)를 돌면서 n개씩 잘라봅니다.
2. 만약 자른 문자열이 같다면 숫자를 세주고, 그에대한 길이를 빼줍니다.
3. 다른 문자열이 나왔다면 현재까지 센 숫자의 길이를 더해줍니다.
4. 해당 문자열의 길이를 전에 구했던 길이와 비교합니다.
> [2021.09.15] 이정규 Programmers H-index, 문자열 압축

- limhizy15/implementation/pro_42747.py
- limhizy15/implementation/pro_60057.py
**풀이**
- 좀 .. 손으로 그리다가 정답이 얻어걸려서 이렇게 푸는게 맞는지 잘 모르겠네요 😓 그리고 왜 정렬 카테고리인지도 잘 모르겠어요 ㅋㅋ 풀이 이상한 부분 있으면 말해주세요 ㅎㅎ
1. 일단 배열을 오름차순으로 정렬했습니다.
2. 이제 배열을 처음부터 순회하면서 배열에서 현재값 이상인 원소가 몇 개인지 구합니다 (cnt). 만약 현재 원소가 cnt보다 크면 이 값이 h이므로 리턴해줍니다.
- 뭔가 설명이 부족한 것 같아서 예시를 들어보겠습니다. [2, 2, 4, 5, 5, 7, 7, 9] 일 때, arr[2] = 4이고 이를 포함한 남은 원소의 개수는 4, 5, 5, 7, 7, 9로 6개입니다. h가 4임이 성립하긴 합니다. 우리는 h의 최댓값을 더 찾아야하므로 한 번 더 이동해봅니다. arr[3] = 5이고 이를 포함한 남은 원소의 개수는 5개입니다. 이 때 h는 5가 됩니다. 그래서 h의 최댓값을 구할 때 `citations[i] == cnt`인 경우가 포함된다고 할 수 있습니다.
- 다른 예시로 [1, 1, 1, 3, 4] 일 때는 비슷하게 arr[3] = 3이고 cnt = 2가 되는데 이 때 h가 2임이 성립합니다. 그래서 위의 예시에 추가해서 `citations[i] >= cnt`인 경우 또한 최댓값을 구할 때 포함됩니다.
**풀이**
- 이건 간단한 구현 문제였던 것 같아요. 코드가 지저분하긴 한데 어찌저찌 답이 구해졌습니다. 며칠 전에 무슨 문젠지 기억 안나는데 마지막 예외처리에서 시간을 잡아먹었었는데요 그 때 해결법을 여기에 쓰니까 그냥 되서 기분이 좋네요 ㅎㅎㅎ
1. 문자열을 자르는 …
> [2021.09.15] 임희지 programmers H-Index, 문자열 압축

- notCoderJ/kakao/str_compression.py
- notCoderJ/sort/h-index.py
h-index가 뭔소린지 이해가 안가서 한~~~참 해멨습니다.😅 제공해준 위키피디아도 여러번 보면서 문제 설명이랑 비교해보다가 문제 설명 무시하고 위키피디아에 나온대로 따라하니 1문제만 틀리더라구요. 그래서 고민하다가 조건에 만족되지 않는 경우를 빼먹은 걸 발견해서 통과했습니다.
풀이 요약
1. 주어진 논문을 역순으로 정렬 후 위키피디아에 나온 h-index를 구하는 식에 따라 (i in n) f(i) >= i를 적용하여 해당 식을 처음 만족하지 않을 때 이전 i(풀이에선 h)값을 반환해줍니다. 
2. 만약 모두 위에 해당하지 않으면 모두 만족하는 것이므로 논문의 전체 길이를 반환합니다.
문자열 다루기는 참... 어려운거 같아요 이전에 풀었던 문제인데 오랫만에 다시 풀어보려니 놓친 부분이 계속 나와서 시간이 꽤 걸렸네요
풀이 요약
1. 1부터 최대 반복가능한 문자열의 길이인 전체 문자열 길이의 반만큼 순회하면서 현재 값만큼의 길이를 갖는 반복할 문자열을 만들고 해당 문자열과 일치하는 문자열이 있는 경우 카운트합니다.
2. 일치하는 문자열이 없는 경우 카운트 값에 따라 현재 반복 문자열 or str(카운트 값) + 현재 반복 문자열을 압축한 문자열에 추가해주고 반복 문자열과 카운트 값을 초기화해줍니다.
3. 압축한 문자열의 길이와 이전 압축 문자열의 길이를 비교해서 작은 값을 answer에 넣습니다.
> [2021.09.15] 전진성 프로그래머스 H-index(lv2), 2020 카카오 블라인드 문자열 압축(lv2)

- JeongGod/programmers/brute_force/search_prime.py
- JeongGod/programmers/kakao/change_bucket.py
풀이는 간단합니다. 순열은 시간복잡도가 O(n!)인데 7자리이하라서 7! 로 충분히 가능하다고 생각했습니다.
소수를 구하는 방법은 2가지로 구현해봤습니다.
1. 에라토스테네스의 체
2. 제곱근을 이용한 소수 판별
에라토스테네스의 체는 소수 판별법중에 가장 빠르다고 알려져있지만 공간복잡도가 그만큼 커진다는 단점이 있습니다.
이번 카카오 코테인지 라인 코테인지 기억이 정확히 나진 않지만 n의 크기가 몇십억이여서 에라토스테네스의 체로는 "메모리초과"가 발생해 해당 방법으로는 풀 수 없었던 문제가 있었습니다.
그래서 그 때 많은 분들이 체로 못 풀어서 당황했다고 하더라구요. 제곱근을 이용한 방식도 익숙해질겸 풀어봤습니다.
<풀이>
1. permutation을 이용해 모든 문자열의 경우의 수를 봅니다.
2. 소수가 가능하다면 집합에 추가해 중복을 제거합니다.
3. 집합의 길이를 리턴합니다.
재귀문제.. 신박하네요. 역시 카카오인가 ㄷ ㄷ
처음에 괄호를 뒤집는다는게 역순으로 나타내다가 시간을 많이 날렸네요.. 모양을 뒤집는다라는걸 질문 게시판을 통해 알았습니다.
문제를 잘 봐야돼요 역시ㅠㅠ
풀이는 요구사항인 그대로입니다. 풀이방법을 던져주고 구현해라. 이건데 말을 참 어렵게도 써놔서 힘들었네요.
<풀이>
1. p를 u, v 로 자릅니다. u는 균형잡힌 문자열이고, v는 나머지입니다.
균형잡힌 문자열은 "더 이상 분리할 수 없다"고 하여서 개수가 같아지면 바로 u, v로 나누는 식으로 진행했습니다.
2. 이 때, u가 올바른지 체크합니다. 
올바른지 판단하는 로직은 스택을 이용해서 여는 괄호와 닫는 괄호의 쌍이 맞는지 …
> [2021.09.16] 이정규 Programmers 소수 찾기, 괄호 변환

- notCoderJ/brute_force/prime.py
- notCoderJ/kakao/trans_paren.py
permutations를 쓰면 간단히 해결되는 문제 같았지만, 라이브러리의 노예에서 벗어나고자 일부러 재귀함수를 구현해서 풀어봤습니다 ㅎㅎ
- `풀이 요약`
에라토스테네스의 체를 이용해 주어진 숫자의 최대 숫자까지의 소수를 구합니다.  
주어진 숫자들의 모든 조합을 구하며 소수인 숫자들을 answer에 추가합니다.  
이후 answer의 길이를 반환합니다.
문제 자체가 해석이 안되서 수십번 읽은 것 같습니다. 괄호 계산하다가 머리 터지는줄 알았네요😇 너무 징글징글한 문제였어요ㅠ
- `풀이 요약`
현재 괄호가 올바른 괄호인지 판단하는 함수와 u, v로 나누는 함수, 괄호를 뒤집는 함수 3개의 함수를 만든 후  
초기 괄호가 올바른 괄호면 바로 반환을 하고
아닌 경우 주어진 절차를 계속 반복하면서  
u가 올바른 괄호면 front에 추가해주고  
아닌 경우 front에는 '('를 back에는 ')' + 뒤집은 괄호를 추가해줍니다.
v가 빈문자열이 되었을 때 front와 back을 합하여 반환합니다.
> [2021.09.16] 전진성 프로그래머스 소수찾기(lv2), 2020 카카오 블라인드 괄호변환(lv2)

- limhizy15/brute_force/pro_42839.py
- limhizy15/implementation/pro_60058.py
- 그냥 문제에서 하라는 대로 구현했습니다! 딱히 생각할 부분이 없었던 것 같아요
1. 문자열을 리스트로 변환한다. 
2. size를 1부터 문자열 길이만큼 반복문을 돌면서 리스트에 대한 순열을 구한다. 
순열의 아이템들을 문자열로 만들어서 집합 s에 넣어준다.
3. 순열이 담긴 집합을 리스트로 바꿔 원소들에 대해 소수를 판별한다. 
(집합 -> 리스트) 이 부분을 간결하게 해보고 싶었는데 못했네요
4. 소수 판별은 그냥 완전 기본적인 알고리즘 써서 설명하기도 좀 그렇네요 ㅎㅎ 에라토스테네스를 잊어버렸어요,, 😓
- 문제 읽는데 80% 쓴 것 같습니다 ^^ 분명 몇 개월 전에 c++로 풀었던 것 같은데 기억이 안나더라구요 ㅎㅎ 이것도 딱히 생각할 게 없고 하라는 대로 구현하는 문제였던 것 같네요! 그래서 풀이 전체를 설명하기보단 부분적으로? 얘기해보겠습니다.
1. 균형잡힌 문자열을 구할 때는 '('가 나오면 cnt를 증가, ')'가 나오면 cnt를 감소시켜서 cnt가 0일 때 잘랐습니다~ 
2. 올바른 문자열을 구할 때는 1번이랑 똑같이 하다가 cnt가 0이하가 되면 (()())) 이런 식으로 짝이 안맞으니까 False를 리턴하게 했고 이제 문자열 탐색 다 끝난 후에 cnt가 0인지 체크하도록 했습니다!
> [2021.09.16] 임희지 programmers 소수 찾기, 괄호변환

- JYP/Programmers_test_kit/is_prime.py
- JYP/kakao_blind/2020_parenthesis.py
- JYP/kakao_blind/2020_parenthesis2.py
- 로직은 문제에 상세히 나와있어서 패스합니다.
- iscorrect 부분을 다르게 구현한 두 파일을 같이 커밋했습니다. 첫번째 파일은 문자열로만 판단한 것, 두번째는 스택 2개를 가지고 판단한 것인데 당연한 소리지만 전자가 코드도 더 짧고 속도도 빨랐습니다.^^; 가독성이나 효율성을 좀 더 고민해봤습니다.
[블로그 기록 - 괄호 변환](https://freckle-alarm-005.notion.site/a71b366072e44492bf931425d1fbd551)
`로직`
- 내장함수 permutation을 사용하면 튜플로 값이 반환되므로, 튜플의 원소를 꺼내서 정수형으로 반환하는 함수 unpack_and_make_digit을 추가했습니다.
- 순열을 이용해 후보 숫자를 구한 뒤 완전탐색으로 소수를 판별합니다. 소수의 개수를 반환해야 하므로 flag 표지를 이용해서 count를 했습니다.
`알게된 점`
- set이 만능이 아닐 수 있다는 걸 이번에 처음 알았습니다.
- 011으로 조합을 한 뒤 set으로 변환했는데 {0, 1, 1, 11, 11, ...} 이렇게 꼭 1이 2개씩 남아서 반환되고 있었습니다. 아마도 실제 숫자 값이 아니라 메모리주소를 기준으로 조합을 하는 것이 아닌가 싶었습니다. 따라서 이를 없애기 위해 다시 result 부분의 로직을 추가했습니다.
[블로그 기록 - 소수 찾기](https://freckle-alarm-005.notion.site/63fcda2bdd8a4e9f9483f841214def68)
> [2021.09.16] 박지윤 - 카카오: 괄호 변환, 프로그래머스: 소수 찾기

- JYP/kakao_blind/2018_the_very_song.py
커밋 메시지 틀렸네요..ㅎㅎ ㅠ 로컬에서 고치려고 amend 해봤는데 vim editor 뭐가 안깔렸다고 자꾸 에러가 나서 오늘은 일단 턴을 넘기겠습니다;;
`로직` 
1) duration: 시간 계산
- 모듈도 있는 줄은 알았는데 그냥 일일이 계산했습니다. 다음에는 모듈을 꼭 써보겠습니다.. datetime.strptime
2) replace_sharp: # 처리
3) play score or score_played: 곡을 재생시간만큼 자르거나 늘리기
4) rotate played score 
- 네오가 알고있는 멜로디와 시작점이 같은 인덱스를 뽑아둡니다.
- deque을 이용하여 그 시작점으로 rotate해서 같은 문자열이 있는지 탐색합니다.
5) '(None)' 처리 ^^...
[걸린 시간은 블로그에 캡쳐이미지 올려뒀어요](https://freckle-alarm-005.notion.site/3-a2af2dd9392f43d4bc617f61678d56c0)
> [2021.09.17] 박지윤 - 카카오: 방금그곡

- JYP/Programmers_test_kit/network.py
- JYP/kakao_blind/2019_openchat.py
- 입력 문자열 = 명령어 + 아이디 + (닉네임)으로 구성
- 입력 문자열의 구조가 가변적인 부분에 대해:
- 풀이 1에서는 if문으로 해결
- 풀이 2에서는 각 작업을 함수로 바꾸어 가변인자로 처리
- 처음에는 백준의 '섬 개수 세기' 문제와 같은 것으로 오해하여 DFS, BFS등을 시도함
- DFS, BFS와 아이디어는 비슷하나 다른 방식으로 풀어야 하는 문제(풀이3 참고)
- 가장 큰 차이는 방문처리 부분:
- 이 풀이에서도 DFS, BFS 문제처럼 visited 배열을 사용하지만
- 한 번 방문한 네트워크 부분은 다시 방문하지 않도록 할 때 기존 배열의 연결값을 1에서 0으로 바꾸는 로직을 추가함
> [2021.10.28] 박지윤 - 프로그래머스: 네트워크, 카카오: 오픈채팅방

- JeongGod/programmers/graph/network.py
- JeongGod/programmers/kakao/open_chatroom.py
dfs로 돌면서 네트워크끼리 이어져있는지 판단했습니다.
<풀이>
1. 먼저 network를 간선리스트 형태로 만듭니다.
2. 그리고 모든 computer를 돌면서 방문하지 않은 컴퓨터라면 새로운 네트워크이므로 네트워크의 개수를 늘립니다.
그 다음, dfs를 돌면서 연결되어있는 모든 컴퓨터를 방문합니다.
userid를 key값으로, nickname을 value로 dict형식으로 풀었습니다.
<풀이>
1. 먼저 모든 records를 돌면서 `userID`(**rest[0]**) 로 일단 진행합니다.
2. 그렇게 모든 records를 돌았으면 `userID`(**rest[0]**)을 그에 맞는 `Nickname`(**rest[1]**)으로 변경합니다.
> [2021.10.28] 이정규 Programmers 네트워크, 오픈 채팅방

- limhizy15/graph_traversal/pro_43162.py
- limhizy15/string/pro_42888.py
문제를 읽어보니 연결된 묶음의 개수를 구하라는 것 같았습니다. 그래서 bfs로 연결된 애들 찾고 몇 개 묶음이 있나 세면 될 거라 생각하고 풀었습니다. 읽어보시면 아주 평범한 bfs알고리즘이라 이해하실 수 있을 거에요!
요것도 구현문제라 하라는 대로 했습니다. 흐름은 record에서 sign, uid, nickname 이렇게 받아와서 sign과 uid만 임시 배열에 저장해뒀습니다. 닉네임은 어차피 마지막에 보면 되기 때문에! 근데 이게 닉네임이 입력에 없는 경우가 있어서 이건 따로 예외처리를 해줬습니다.
근데 Change가 아니고서도 닉네임이 바뀌면 무조건 uid에 맞게 바꿔줘야하더라구요 그 부분 놓쳐서 시간을 조금 썼습니다 ㅎㅎ Change인 경우도 혹시몰라서 처리해줬어요
> [2021.10.30] 임희지 programmers 네트워크, 오픈채팅방

- JYP/Programmers_test_kit/stepping_stone.py
- JYP/kakao_blind/2018_cache.py
- 대소문자 구분 없애기 >> 소문자로 통일
- Cache Hit
: 캐시에서 가장 최신 위치로 올려주고 시간 계산하기
: 원래 데이터 순서대로 정렬한 뒤 캐시의 최신 위치에 지금 읽은 값 추가
- Cache Miss
: 예외 처리 - 캐시 사이즈가 0이면 계속 캐시 미스가 발생하므로 5초씩 추가
: 캐시가 꽉 찼다면 먼저 캐시에서 오래된 데이터를 제거하기
: 캐시 및 참조 맵에 데이터 추가
- 바위의 거리를 대상으로 이진탐색
1. 바위들을 위치 순으로 정렬
2. mid보다 현재 바위 간 거리가 짧으면 지금 바위를 제거 : cnt += 1
3. cnt가 제거 가능한 바위 개수 n값보다 크다면 mid 증가
4. cnt가 n값보다 작다면 mid 감소
5. 카운트하는 동안 저장한 거리의 최솟값 반환하기
징검다리에서 제일 오래 걸렸네요^^; 
커밋 보시면 풀이 2번과 같은 방식을 처음에 시도했지만 당연히 전체 거리를 따지고 다시 바위를 제거하고 또 거리를 따지는... 방식은 런타임 에러가 났구요.
바위의 거리를 대상으로 이진 탐색한다는 말이 어떤 의미인지 잘 이해가 안돼서 문제 풀이에 시간이 좀 걸렸습니다.
이해한 내용은 주석 및 위의 코멘트로 정리해두었어요.
> [2021.11.01] 박지윤 프로그래머스-징검다리, 카카오-캐시

- limhizy15/data_structure/pro_17680.py
- limhizy15/two_pointer/pro_43236.py
LRU.. 문제가 굉장히 불친절하네요!! 알고리즘 설명은 해주지! 그냥 간단하게 오래된 애들을 없애는 식으로 구현했습니다. 배열로 구현하려다가 사용이 불편해서 deque을 썼는데 괜찮은건지 모르겠네요
- 먼저 캐시 크기가 0이면 무조건 실행시간이 5이기 때문에 개수 * 5로 리턴해줍니다.
- 그 다음 cities를 돌면서 city가 cache에 있는지 확인합니다. 존재하지 않으면 해당 도시의 이름을 캐시에 넣고 캐시 크기를 넘어가면 맨 앞에 있는 도시를 빼줍니다. 
- 만약 해당 도시가 캐시에 있으면 빼고 맨 뒤로 넣습니다. 최신순으로 두기위해~
찾아보고 이해했다고 생각했는데 막상 풀이를 쓰려니까 다시 모르겠네요.. 이분 탐색은 어떤걸 시작점, 끝점, 타겟으로 둘지 너무 어려운 것 같아요.. 
- 일단 이진탐색을 위해서 rocks를 정렬해줍니다. rocks를 돌면서 기준점이 되는 돌이랑 그 사이를 구해서 mid보다 작으면 돌을 제거하고, 아니면 기준돌의 위치를 현재 돌로 바꿔줍니다.
- 만약 제거한 돌이 n보다 크면 문제에 어긋나니까.. end를 mid -1로 옮기고 아니면 start를 mid +1로 옮깁니다.
> [2021.11.01] 임희지 programmers 캐시, 징검다리
