limhizy15/elice_study

limhizy15/brute_force/14501.py, limhizy15/brute_force/2961.py
두 문제 다 재귀를 활용한 완전탐색으로 풀었습니다.
프로그래머스 [타겟 넘버](https://programmers.co.kr/learn/courses/30/lessons/43165) 문제 솔루션을 재활용했습니다. 
```c++
#include <string>
#include <vector>
using namespace std;
int answer = 0;
int Target;
void DFS(vector<int>& num, int sum, int cnt){
if(cnt == num.size()){
if(sum == Target) answer++;
return;
}
DFS(num,sum+num[cnt],cnt+1);
DFS(num,sum-num[cnt],cnt+1);
}
int solution(vector<int> numbers, int target) {
Target = target;
DFS(numbers, 0,0);
return answer;
}
```
`14501 : 퇴사`
이 문제의 경우 어느 날짜 k일에 상담을 한다 or 안한다를 결정하는 방식으로 풀었습니다.
1일씩 더하면서 탐색하는 것이 아니라 
1) 상담을 하면 : 필요한 기간만큼 더한 후 탐색
2) 상담을 안하면 : 1일 더한 후 탐색
이렇게 풀었습니다.
`2961 : 도영이가 만든 맛있는 음식`
이것도 퇴사랑 로직은 똑같습니다. 재료 n개가 있을 때 k번째 재료를 선택한다 or 안한다를 결정하는 방식으로 풀었습니다.
그런데 제가 이걸 풀면서 막혔던 부분이 **line37,38 부분을 보면 s=1, b=0을 강제로 예외처리**를 했습니다.
재귀를 …
=> [2021.07.19] 임희지 BOJ 14501, 2961

notCoderJ/brute_force/1018.py, notCoderJ/brute_force/19699.py
두 방법 모두 answer를 집합으로 구현해 중복되는 무게를 제거했습니다.
- `방법 1. 조합을 이용한 풀이`
n과 m의 범위가 9이하이고 각 무게가 최대 1000이므로 소수를 구하는데 약 90회 연산 * nCm의 시간 복잡도이므로
완전 탐색을 통해 문제를 해결할 수 있다고 생각했습니다.
1. 주어진 n마리의 소 중 m마리를 선택하는 모든 경우의 수를 구합니다.
2. 1번의 각 케이스마다 소들의 무게 합을 구하고 소수인지 판별합니다.
2-1. 소수를 판별하는 함수를 재귀함수로 구현했습니다.(어떤 수의 약수는 제곱근을 기준으로 대칭되므로 이를 이용했습니다.)
3. 2번에서 구한 소수가 없는 경우 -1, 있는 경우 오름차순으로 출력합니다.
- `방법 2: 재귀함수를 이용한 풀이`
너무 조합으로만 푸는 느낌이 들어 희지님이 사용하셨던 '선택 vs 미선택' 방식을 채용해서 재귀로 구현해봤습니다.
다음에는 정규님이 사용하시던 '재귀 + for'도 도전해보겠습니다.
1. 선택해야할 소의 수, 현재 선택 가능한 소의 수, 현재 무게의 합을 입력받는 재귀 함수를 수행합니다.
2. 현재 해당하는 번째의 소를 선택하는 경우와 선택하지 않는 경우에 대해 다음과 같이 값을 갱신하여 1번을 반복 수행합니다.
- 선택한 경우 : 선택해야할 소의 수 - 1, 현재 선택 가능한 소의 수 - 1, 현재 무게 + 현재 선택한 소의 무게
- 선택하지 않은 경우 : 선택해야할 소의 수, 현재 선택 가능한 소의 수 - 1, 현재 무게
3. 선택해야할 소의 수가 0인 경우 소수인지 검사해서 answer에 넣어주고 현재 선택 가능한 소의 수가 …
=> [2021.07.21] 전진성 BOJ 1018, 19699

JeongGod/1018.py, JeongGod/19699.py
1. 8*8의 체스판을 모두 돌아보면서 확인하는 것으로 했습니다.
2. 최대 50*50의 체스판을 8*8의 체스판으로 둘러보는걸로 하였습니다.
3. 8*8의 체스판을 둘러보는 기준은 board[0][0] = "W" or "B"로 그 기준을 정했습니다.
- 만약 board[0][0] = "W" 라면 
board[짝수][홀수] = "B"
board[짝수][짝수] = "W"
board[홀수][짝수] = "B"
board[홀수][홀수] = "W"
로 만약 다르다면, 해당 체스판을 다시 칠해야 하는 것으로 하였습니다.
board[0][0] = "B"는 위와 동일한 로직으로 진행됩니다.
4. 이게 곧 (50-8+1)(50-8+1)만큼 돈다. 그래서 총 시간복잡도는 O(2*(8*8) * 43 * 43)으로 충분히 돌 수 있다.
n이 작아서 숫자로 시간복잡도를 표현해봤습니다.
1. 소수를 판단하는 기준으로는 "에라토스테네스의 체"를 이용했는데 알고리즘이 어렴풋이 기억나서 생각대로 적어봤더니 정확하지 않네요.. 
정확한 코드는
```python
for i in range(2,9001):
if prime[j]:
for j in range(2*i, 9001, i):
prime[j] = False
```
소수를 구하는 코드중에서는 가장 빠르다고 합니다. O(n log log n)이라고 하네요.
2. 조합의 합이 소수라면, 중복을 제거하기 위해 집합에다가 넣었습니다.
3. 그리고 집합을 정렬한 뒤 출력합니다.
=> [2021.07.21] 이정규 BOJ 1018, 19699

JeongGod/17129.py, JeongGod/21938.py
BFS로 풀었습니다. 총 시간복잡도는 900만으로 충분히 가능하다 생각하고 풀었는데 자꾸 "시간초과"가 나서 많이 헤맸습니다..
python3로는 절대 못 푸는 문제였고, pypy3로 풀어야 하는 문제였던걸 알았습니다ㅠㅠ
하지만 pypy3에서도 "메모리 초과"로 통과되지 못했고 이유는 이러했습니다.
```python
dq.append((ans, px, py))
```
이런식으로 ans가 현재 시작점 거리로부터 얼마나 떨어져 있느냐의 변수로 같이 deque에 넣었습니다. 
이로 인해 메모리가 초과가 발생하였고 해결책으로 visited를 시작점과의 거리로 저장하여 방문했냐 안했냐를  판단하였습니다. 
그렇게 deque에 넣는 변수를 줄이니 통과되었습니다.
c++에서는 저렇게 컨테이너에 복잡한 메모리를 집어넣는다면 그만큼 연산과 삭제에서 시간이 많이 걸린답니다. 오늘 진성님처럼 pypy3는 재귀에 약하다는 특성이 있는 것 처럼 무조건 pypy3를 사용하는 것이 아닌 언어적 특성을 이해하는 것도 필요한 것 같습니다.
- 풀이
1. 시작점을 찾는다.
2. 시작점을 deque에 넣고, 상하좌우 좌표를 넣습니다.
3. 해당 좌표가 음식이라면 함수를 종료시킵니다.
4. deque이 비어있을 때 까지 반복합니다. 
해당 문제도 BFS로 풀었습니다.
- 풀이
1. rgb는 3가지의 색상이므로, 입력받을 때 3개씩 쪼갠 뒤 합쳐서 그의 평균을 바로 냈습니다.
2. 위에서 받은 값을 기준과 비교하여 작다면 0으로 만들어 물체가 아니게 표시했습니다.
3. 물체를 찾으면 수량을 증가시키고, BFS형식으로 돌리면서 해당 물체를 0으로 …
=> [2021.07.26] 이정규 BOJ 17129, 21938

notCoderJ/dfs_bfs/17129.py, notCoderJ/dfs_bfs/21938.py
`###  17129: 윌리암슨수액빨이딱따구리가 정보섬에 올라온 이유`
이동 경로 간 가중치가 1이고 최단 거리를 구하는 문제이므로 bfs를 이용하면 되겠다고 생각했습니다.
1. 주어진 맵 정보를 입력받으며 값이 2인 경우 시작점에 해당하므로 deque의 시작 값으로 넣어줍니다.(이때 deque에는 현재 좌표 x, y와 해당 지점의 값, 현재 지점까지 거리 정보를 넣어줍니다.)
2. deque이 비거나 최단 경로에 있는 음식점을 찾을 때까지 bfs를 반복 수행합니다.
2-1. 현재 지점에서 상하좌우에 있는 지점 중 주어진 맵을 벗어나지 않고 빈 복도이거나 해당 지점 값이 2보다 큰 경우에 대해서 다음을 수행합니다.
- deque에 해당 지점 좌표와 지점 값, 현재까지 거리 + 1을 추가하고 해당 지점 값을 1로 변경하여 지나갈 수 없는 지역으로 만들어 줍니다.(방문처리)
`###  21938: 영상처리`
bfs나 dfs 둘 다 가능하겠다고 생각하여 먼저 dfs를 시도하였습니다. 처음에는 주어진 맵을 모두 입력받고 방문처리용 테이블도 하나 만들어 시도하였지만 메모리 초과로 1차 실패.
그래서 방문처리용 테이블을 삭제하고 주어진 맵을 그대로 이용하는 방법으로 시도하였으나 메모리 초과로 2차 실패.
아예 처음부터 입력받으면서 평균을 구해서 저장해놓고 비교하였으나 메모리 초과로 또 실패. 반복적인 메모리 초과로 멘탈이 붕괴됬다가 파이썬으로 다시 제출해보니 성공...??
그래도 메모리 사용량이나 수행 속도를 보니 bfs가 낫겠다고 생각하여 다시 bfs로 풀었습니다.
1. dfs 풀이
n * m 픽셀을 하나씩 탐색하며 …
=> [2021.07.26] 전진성 - BOJ 17129, 21938

notCoderJ/dfs_bfs/18352.py, notCoderJ/dfs_bfs/7576.py
익은 토마토를 기준으로 안익은 토마토까지의 가장 먼거리를 계산하면 되겠다고 생각했습니다.
먼저 주어진 정보를 입력받으면서 익은 토마토의 좌표를 deque에 넣어두고 안익은 토마토의 갯수를 카운팅합니다.
그 후 deque이 비거나 안익은 토마토가 없을 때까지 다음 과정을 반복 수행했습니다.
- deque에서 하나씩 꺼내어 상하좌우에 있는 안익은 토마토에 대해 (해당 토마토 좌표, 현재일자 + 1) 값을 다시 deque에 넣어줍니다.
- deque에 넣어준 토마토는 값을 계산한 day로 바꾸어주어 재방문 하지 않도록 합니다.
- 안익은 토마토의 갯수를 1 감소시킵니다.
어디서 본 것 같은 문제라는 생각이 들었는데, 제출하고 보니 얼마 전에 풀었던 문제더라고요
다시 한번 처음부터 풀어보았습니다 ㅎㅎ
일단 방향성 있는 그래프에서 최단거리를 구하는 문제이고 이동 가중치가 1이라서 bfs, 다익스트라 둘다 가능하다고 생각했습니다.
- 다익스트라 풀이
시작점부터 시작하여 다음 과정을 반복 수행합니다.
연결된 각 도시들에 대해 해당 도시까지의 거리를 계산하고 현재 거리보다 작은 경우
해당 도시까지의 거리를 갱신하고 heapq에 (거리, 도시) 값을 추가해줍니다.
heapq에서 꺼낸 도시 중 거리가 k인 도시는 answer에 추가하고
k보다 클 경우 더 이상 k보다 짧은 거리는 나오지 않으므로 반복을 종료합니다.
answer이 비어있으면 -1 존재하면 오름차 정렬 후 각 도시 번호를 출력해줍니다.
- bfs풀이
전반적으로 다익스트라와 비슷한 로직을 띄고 있고 2가지 차이점이 있습니다.
1. heapq 대신 deque을 …
=> [2021.07.27] 전진성 - BOJ 7576, 18352

JeongGod/18352.py, JeongGod/7576.py
BFS로 풀었습니다.
visited대신에 board에 토마토까지 된 걸린 시간을 업데이트하여 방문했는지 안 했는지를 판단했습니다.
BFS로 풀었습니다. 
DFS형식으로 풀어볼라 했지만 안되더군요. 최단거리만을 기억하고 있어야 해서 문제였습니다. 그 뒤에 로직은 제가 생각을 못하겠어서 포기했네요.
처음에 메모리 초과로 힘들었는데 도시끼리의 연결을 n*n으로 표현하다보니, 90억개의 리스트로 메모리초과가 났습니다. 보통 1억개의 크기면 381MB라네요. 
또, k의 범위가 1부터 300,000으로 생각하고 풀었는데 자꾸 70%에서 틀렸다고 나와 힘들었네요. k=0인 테스트케이스도 있는 것 같습니다. 그래서 문의를 넣긴 했는데.. 제가 틀린 건지 한 번 봐주시면 감사하겠습니다!
line 15 ~ 17대신 이렇게 넣으면 틀립니다. 같은 로직이지 않나요..? 만약 k가 1이상이면 성립하는 로직같다고 생각합니다.
```python
visited[x] = True
for node in board[x]:
dq.append((node,1))
visited[node] = True
```
마지막 출력할 때, join사용을 위해서 답을 string형으로 바꾸니 또 틀렸다고 해서 많이 헤맸네요.ㅠㅠ 정해진 형식을 맞춰야 하는 것 같습니다..
=> [2021.07.27] 이정규 BOJ 7576, 18352

JeongGod/pro_change_word.py, JeongGod/pro_journey.py
<풀이>
1. 처음 시작 단어에서 하나씩 빼놓고 다 자릅니다.
2. 그렇게 다 자른 뒤 단어들과 비교하기 전에 방문 여부를 판단합니다. 해당 단어를 이미 거쳐갔다면, 다시 거칠 필요가 없어 처리했습니다.
3. 단어의 시작과 끝이 처음 잘라놓은 단어와 일치하는지 판단하여 바뀔 수 있는지를 판단합니다.
4. 바뀐다면 다시 덱에 넣고 해당 단어를 돌립니다.
line 22, 27은 쓸모없는 코드네요.. 무시해주세요ㅠㅠ
정말 로직은 짜지는데, 코드로 옮기는게 힘드네요. dfs는 머리로 생각하는게 너무 힘든 것 같습니다ㅠㅠ 결국 구글링해서 풀긴 했습니다..
<풀이>
1. 처음 시작점인 "ICN"과 연결된 공항을 방문합니다.
2. 만약 다른 곳과 연결되지 않은 끊어진 공항을 만났다면, None을 return합니다.
3. None을 return하였다면, 다시 티켓을 원상복구합니다.
4. 그렇게 모든 티켓을 다 도는 경로를 return합니다.
---
전에 설명드렸다시피 파이썬의 객체 복사에 대해서 말씀드렸는데 deepcopy라는 것을 발견해서 무엇인가 찾아보니 많더라구요.
```python
import copy
```
를 사용하면 이제 "얕은" 복사와 "깊은" 복사가 존재하는데 이는 전에 "=" 대입연산과는 다른 복사더라구요. 이번에 deepCopy라고 주석을 달아놓은 부분이 있는데 설명드리겠습니다.
"깊은" 복사는 복합객체를 새롭게 생성한 뒤, 재귀적으로 값까지 복사하는 경우입니다. 완전히 다른 객체로 분류되어서 전에 말씀드렸던 값이 따라서 바뀌는 경우가 없더라구요.
"얕은" 복사는 복합객체를 새롭게 생성하지만, 그 …
=> [2021.07.28] 이정규 프로그래머스 단어변환, 여행경로

JeongGod/2206.py, JeongGod/7569.py
"벽을 부순 경우" 와 "벽을 부수지 않은 경우"의 경로를 나눠서 생각했습니다. 처음에는 합쳐서 생각하다 틀려서 질문게시판을 봤네요.
<line 50 ~ 51>
벽을 부수지 않은 경우에서 벽을 부순경우도 같이 업데이트 하는 이유는, 벽을 부순 경우에서의 경로 길이 == 벽을 부수지 않은 경로 길이이기 때문입니다.
결국, 벽을 부순 경우에서 다시 벽을 부수지 않은 경로를 가는 곳은 비효율적이라고 판단해서 짜봤는데 없나 있으나 시간은 50ms밖에 차이가 안나네요. 
<풀이>
1. 현재 위치에서 상하좌우가 가능한지 탐색합니다. 이전에 벽을 뚫었다면, wall_visited에서 가능한지 탐색합니다.
2. 벽을 부수지 않았다면, 일반 visited에 표시합니다. 벽을 "이전에" 부숴놨다면 wall_visited에 표시합니다. 
3. 만약 통과가능한 곳이라면, 벽을 뚫어서 통과했는지 판단하여 덱에 넣습니다.
4. 위를 반복하여 끝점에 다다르면 , 가장 최적의 값이므로 return합니다.
로직은 저번 토마토와 같습니다. 3차원이라고 해서 상하좌우 + (위층, 아래층)을 추가하여 진행했습니다.
=> [2021.07.29] 이정규 BOJ 2206, 7569

limhizy15/graph_traversal/2206.py, limhizy15/graph_traversal/7569.py
얼마전에 푼 토마토랑 로직은 똑같습니다. 
1. n * m * h 배열에 토마토 정보를 입력 받는다. (보드)
2. 보드를 탐색하면서 1인 곳의 좌표를 덱에 담는다.
3. BFS탐색
-> 덱 가장 앞의 요소를 꺼낸다.
-> 6방향을 탐색한다. (2차원 기준 상하좌우, 3차원 기준 위아래)
-> 다음 좌표가 보드의 영역을 벗어나거나 0이 아니어서 이미 익은 토마토이면 스킵
-> 아닌 경우 방문해서 토마토 값을 기준 토마토 + 1로 갱신해주고 덱에 좌표 삽입
4. 탐색이 끝나고 보드를 돌면서 아직 익지 않은 곳이 있는지 체크 & 가장 큰 값을 찾아서 필요한 일수를 구함
- 3차원 입력은 감이 안와서 구글링해서 찾았습니다!
```python
board = [[list(map(int, input().split())) for _ in range(n)] for _ in range(h)]
```
---
처음에는 그냥 벽을 하나도 부수지 않은 상태에서 bfs탐색하고, 보드를 탐색하면서 벽을 지우고 bfs탐색하는 방법을 생각했는데 n, m이 최대 1000이라 안돌아갈 것 같았습니다. (정확한 시간복잡도는 모르겠네요 ㅎㅎ)
그러다가 그럼 벽을 부순 경우와 부수지 않은 경우를 나눠야겠다고 생각했고 방문을 체크하는 visited 배열을 두개 만들었는데, 이렇게 하니까 헷갈리더라구요.. 그래서 visited[i][j][0] 이런식으로 방문배열을 만들었습니다.
설계 하는게 어려웠어요.. 그래서 중간중간 검색을 좀 했습니다 ㅎㅎ
`빈칸 to 빈칸`은 항상 가능
`빈칸 to 벽`은 아직 한 번도 벽을 부순 적이 없으면 이동 가능
`벽 …
=> [2021.07.29] 임희지 BOJ 7569, 2206

notCoderJ/dfs_bfs/2206.py, notCoderJ/dfs_bfs/7569.py
허허.... 처음에 쉽게 생각하고 접근했다가 한참 헤맸네요...😂
벽 부순 경우랑 안 부순 경우를 한 맵 안에서 처리하려고 끝없이 시도하다가... 결국 포기하고
구글님께 힌트를 얻어 맵 두개로 분할하는 방식으로 겨우 통과헀네요 ㅎㅎ
일단 로직은 벽을 부순 맵이랑 안 부순 맵을 두개 만들어놓고
방문하지 않은 경로(통로이거나 벽이면 부순적 없는 경우)에 대해 탐색하면서
벽을 부순 경우는 벽을 부순 맵에 현재까지 이동 거리를 표기하고
벽을 부수지 않은 경우는 부수지 않은 맵에 이동 거리를 표기하며 bfs를 수행합니다.
두 경우 중 n, m의 위치에서 작은 값을 출력합니다.(단, 둘 중 하나가 0일 경우는 0이 아닌 값을, 둘 다 0인 경우는 -1을 출력합니다.)
지난 번 토마토 문제의 3차원 확장판이었기 때문에 간단하게 풀이했습니다. 앞뒤 고려사항이 추가된 것 외엔 지난 번 토마토와 동일하기 때문에 풀이 과정은 지난번과 같습니다.
먼저 주어진 정보를 입력받으면서 익은 토마토의 좌표를 deque에 넣어두고 안익은 토마토의 갯수를 카운팅합니다.
그 후 deque이 빌 때까지 다음 과정을 반복 수행했습니다.
- deque에서 하나씩 꺼내어 상하좌우, 앞뒤에 있는 안익은 토마토에 대해 (해당 토마토 좌표, 현재일자 + 1) 값을 다시 deque에 넣어줍니다.
- deque에 넣어준 토마토는 값을 계산한 days로 바꾸어주어 재방문 하지 않도록 합니다.
- 안익은 토마토의 갯수를 1 감소시킵니다.
=> [2021.07.29] 전진성 BOJ 2206, 7569

JeongGod/1504.py, JeongGod/1717.py, JeongGod/20168.py, JeongGod/9370.py
시작점, 도착점의 최단 경로를 구하라고 해서 다익스트라로 구현하겠다고 생각했습니다.
그리고 두 개의 정점을 무조건 지나야 하고, 지났던 곳은 다시 가도 된다는 조건을 보고 다익스트라를 3번 사용하면 되겠다라고 마음먹고 짰습니다.
<풀이>
1. 시작점 "1"에서 다익스트라 알고리즘으로 최단거리를 구한다.
2. `1번`에서 구한 최단거리 중 거쳐야 하는 정점 [M1, M2]중 하나로 출발점을 잡고 다익스트라 알고리즘으로 최단거리를 구한다.
3. `2번`에서 구한 최단거리 중 정점 [M1, M2]중 거치지 않은 정점을 출발점으로 잡고 최단거리를 구한다.
4. `1 -> M1 -> M2 -> N`, `1 -> M2 -> M1 -> N`중에서 작은 값을 출력한다.
처음에 대표 노드를 놓고 트리형식으로 하면 될 것 같았는데 어떻게 해야 할 지 감이 잡히지 않아 구글링을 했습니다.
크루스칼 알고리즘에서 쓰이는 Union-find 알고리즘을 공부하여 썼습니다.
<풀이>
1. 집합을 합친다면
1. 합칠 집합 가장 최고인 부모를 찾습니다.
2. 해당 부모가 같다면, 같은 집합내에 있다는 뜻이므로 진행하지 않습니다.
3. 부모가 다르다면, Rank를 기준으로 합칩니다. 나중에 find할 때 이점을 주기 위해서입니다.
2. 같은 집합에 있는지 확인한다면
1. 각 집합의 가장 최고인 부모를 찾습니다.
2. 해당 부모가 같다면, 같은 집합내에 있다는 뜻입니다.
---
dfs로 풀어봤는데 몇 개의 케이스에서 시간초과가 났는지 맞았지만 다 못 맞은 문제로 뜨네요.
문제 태그를 보니 백트래킹이라고 써있어서 조건을 추가하면 될 것 같은데 …
=> [2021.08.03] 이정규 BOJ 1504, 1717

notCoderJ/graph/1504.py, notCoderJ/graph/1717.py, notCoderJ/graph/20168.py, notCoderJ/graph/9370.py
**`1504: 특정한 최단 경로`**
처음에는 경로를 거쳐간다고 하여 플로이드 워셜을 생각했습니다. 하지만, 노드가 최대 800개라 3중 for문을 돌리면 터질 것이기 때문에 포기하였고 각각의 경로로 가는 최단 거리를 구해서 합하면 해당 지점을 거쳐가는 최단 거리가 나올 것이라 생각하여 각 지점에서 다익스트라를 수행 후 경로의 합이 최소인 지점을 선택하는 로직으로 설계하였습니다. 그러나 코드를 짠 후 계속 실패가 나와서 구글링을 해보았는데 로직 자체가 동일하더라구요;
그래서 왜 안되지 고민하다가 플래그를 뒀던 것을 제거해보았는데 통과되네요;
아래 코드 line 34 ~ 39 주석 부분이에요... 혹시 왜 그런지 아시는 분 계신가요ㅠ?
line 58~59는 굳이 1 -> n1 -> n2 -> n1 -> n 이런 경우를 생각할 필요가 없었네요 이게 최단경로를 구하면 포함되서 나오는걸 미처 생각못했어요 ㅎㅎ;
**`1717: 집합의 표현`**
합집합 연산과 같은 집합에 속해있는 지 확인하는 것으로 보아 서로소 집합 알고리즘이라는 것을 알았습니다.
그래서 주어진 합집합 연산에 대해서는 a, b를 합집합 연산해주었고 같은 집합에 속해있는지 확인하는 것은
두 노드의 루트 노드를 검색해서 사이클이 발생하는지 여부를 확인하여 판별했습니다.
**`9370: 미확인 도착지`**
풀어보니 문제 유형은 어제 풀었던 <1504: 특정한 최단 거리>와 매우 비슷한 문제였습니다. 하지만, 처음에는 문제 자체가 잘 이해되지 않아 조금 헤맸습니다. 해당 경로를 거쳐가는 최단 거리를 구하라는 문제같긴 헀는데, 예시 1, 2번의 출력된 …
=> [2021.08.03] 전진성 BOJ 1504, 1717

JeongGod/1261.py, JeongGod/13549.py, JeongGod/TwoPointer/11659.py, JeongGod/TwoPointer/1806.py, JeongGod/TwoPointer/2470.py
<문제>
무기를 이용하여 벽을 부술 수 있습니다.
빈방은 자유롭게 다닐 수 있습니다.
1,1 부터 N,M까지 가려면 벽을 최소 몇 개 부숴야하는지 출력하세요.
---
<풀이>
BFS와 비슷한 로직처럼 Dijkstra를 구현했습니다.
1. 가장 적게 벽을 부순 위치를 뽑습니다.
2. 상하좌우를 확인하여 가지 않은 곳을 확인합니다.
3. 벽을 부쉈는지 안 부쉈는지 판단하여 hq에 넣고 방문처리를 합니다.
4. 1번부터 반복하다, 만약 도착지점이 나왔다면 최소로 벽을 부수고 나온 것이므로 리턴합니다.
아마 BFS로도 구현이 가능할 것 같은데 처음 생각이 이거로 나서 짰습니다!
start = 시작 위치, Dest = 목적지
<문제>
걷는다면 1초후에 X-1 or X+1의 위치로 이동.
순간이동을 한다면 0초후에 2*X의 위치로 이동
목적지에 가장 빠르게 도달하는 시간을 출력하세요.
---
<풀이>
BFS로 풀었습니다.
1. 처음 시작 위치를 넣습니다.
2. 처음 시작위치에서 +1, -1은 시간을 1초 늘리고, *2는 시간을 늘리지 않고 방문처리를 합니다.
3. 계속해서 1번을 반복하여 모든 곳을 다 방문합니다.
4. 답을 리턴합니다.
지금 보니깐 BFS라서 모든 경로를 보지 않아도 되고 도착지점에 도착하면 그게 최단거리라서 되네요. 전에 이렇게 짰었는데 왜 생각을 못하는지..  저 min하는것도 빼버려도 되네요..
---
좀 많이 해멨네요.. 이거 밑에 2문제를 먼저 푼 뒤에 풀어서 그런지 어떻게 해야할 지 감이 잡혔던 것 같습니다.
실전에선 멘탈 나갈거같네요..
<풀이>
11659문제처럼 풀면 되겠다고 …
=> [2021.08.05] 이정규 BOJ 1261, 13549

notCoderJ/binary_search/10815.py, notCoderJ/binary_search/16564.py, notCoderJ/elice/rolling_ball.py
음... 이 문제는 주어진 입력의 수가 최대 50만이고 중복되는 숫자 카드가 없으므로 간단히 집합 자료형을 이용한 순차 탐색으로 해결할 수 있다고 생각했습니다. 하지만, 이번주의 취지가 이분 탐색 알고리즘 능력을 향상시키기 위함이므로 이분 탐색을 구현해서도 풀어봤습니다.
- 총 3가지의 풀이 방식으로 풀었습니다.
1. 집합 자료형을 이용한 순차 탐색 풀이
n개의 숫자에 대한 집합을 만들고 주어지는 m개의 숫자를 하나씩 순회하며 해당 집합에 들어있는지 확인하여 0 또는 1을 출력합니다.
2. 직접 이분 탐색을 구현한 풀이
처음에는 이분 탐색 함수에 리스트를 슬라이싱하여 분할된 리스트를 매개 변수로 전달하는 방식으로 구현헀는데, 슬라이싱 과정에서 시간이 많이 소요되어 시간 초과 판정을 받았습니다. 그래서 이분 탐색 함수에 시작, 끝 인덱스를 전달하고 해당 인덱스를 통해 중간 인덱스를 구하여 탐색하는 방법으로 다시 구현했습니다.
이 방법은 통과는 되었으나, 이분 탐색임에도 1번 알고리즘보다 효율성이 많이 떨어지더라구요... 아마 초기에 n개의 숫자를 정렬해야하기 때문인 것 같습니다.
3. 이분 탐색 모듈(bisect)를 이용한 풀이
bisect 모듈을 간단히 설명하면
- bisect_left(리스트, 대상 값) : 매개 변수로 주어진 정렬된 리스트에 대상 값이 들어갈 좌측 인덱스를 반환합니다.
- bisect_right(리스트, 대상 값) : 매개 변수로 주어진 정렬된 리스트에 대상 값이 들어갈 우측 인덱스를 반환합니다.
ex) a = [1, 2, 6, 10]이 있을 때 bisect_left(a, 2) = 1 / …
=> [2021.08.09] 전진성 BOJ 10815, 16564(+엘리스 공굴리기)

JeongGod/BinarySearch/13397.py, JeongGod/BinarySearch/7453.py, JeongGod/TwoPointer/20922.py, JeongGod/TwoPointer/3151.py
처음에 투포인터 + 이분탐색으로 접근했는데 중복되는 값을 처리를 못 하겠더라구요.. 그래서 그냥 투포인터로만 풀었습니다.
중복처리에서 애를 많이 먹었네요. 시간초과를 어떻게 해결하나.. 하면서 많이 애먹고 결국 구글링해서 알아낸 문제입니다.
<풀이>
1. 먼저 투포인터를 사용하기 위해 sort를 합니다.
2. "i"번째 학생을 선택했을 경우의 값을 goal로 설정한다면 `left번쨰 학생 + right번째 학생 + goal == 0`을 찾도록 합니다. 
3. 저 위의 식을 생각하면 `left + right = -goal`로 놓고 left + right값을 비교해나가면서 포인터를 이동시킵니다.
4. 만약 left ~ right까지 모든 학생이 같다면 조합을 생각했습니다. 같은 것에서 2개를 뽑는 것이니 조합식을 이용하여 구현했습니다.
`nCr = n! // (n-r)! r!`
5. 그리고 부분적으로 같은 값을 가지고 있는지 확인합니다.
- 저 시간초과난 코드는 right에서 이미 중복을 검사했다면, 다시는 검사하지 않아도 되지만 계속해서 검사하다보니 시간초과가 났습니다.
<풀이>
1. list를 돌면서 숫자와 그 숫자가 있는 index를 받아옵니다.
2. dict에 key를 숫자로 하여금 index를 넣습니다. dick[num] 에 있는 list의 길이는 곧 num의 개수입니다.
3. 만약 현재 순열에서 num의 개수가 k개를 넘어가는 부분이라면 현재 left(수열의 시작부분)와 비교합니다. left보다 작다면 순열에 포함되지 않는 부분이므로 해당 index를 제외하고 다음 반복문으로 넘어갑니다.
4. 그리고 …
=> [2021.08.12] 이정규 BOJ 3151, 7453, 13397, 20922

notCoderJ/data_structure/db_priority_q.py, notCoderJ/data_structure/disk_controller.py
풀이요약
최대 힙과 최소 힙 2개의 힙을 생성하고 현재 데이터의 갯수를 카운팅할 딕셔너리를 생성해서 연산을 수행했습니다.
자료의 삽입 명령인 경우 최대 힙과 최소 힙에 모두 넣어주고 카운트 딕셔너리의 해당 값을 key로 하는 값으 1 증가시켜 줍니다.
삭제 연산인 경우 각 경우에 대해 최대 힙이나 최소 힙 둘 중 하나의 힙에서 자료를 삭제하고 카운트 딕셔너리를 갱신해줍니다.
모든 연산을 수행 후 카운트가 0이 아닌 값들(key)만 필터링한 후 값이 있으면 [최댓값, 최솟값]을 출력하고 없으면 [0, 0]을 출력했습니다.
다른 분들의 풀이를 보다가 좋은 풀이가 있어서 2개정도 가져와봤습니다.
- 풀이 2
heapq의 성질을 잘이용한 풀이네요.
최소힙을 하나 구현하여 해당 힙에 주어지는 자료들을 모두 넣어줍니다.
삭제 연산의 경우 최솟값을 빼줄 때에는 heapq의 heappop 연산을 수행하고
최댓값을 빼줄 때에는 list의 remove 연산을 통해 힙의 최대값을 지정하여 삭제해줍니다.
이렇게 해도 가능한 이유는 힙에서 remove연산을 수행해도 결국 리스트이기 때문에 현재 최솟값의 위치는 변하지 않고, heappush가 수행되면 heap을 다시 유지시켜주기 때문에 가능한 풀이같습니다.
- 풀이 3
이 풀이는 제가 풀었던 것과 같이 최소 힙과 최대 힙 2개의 힙을 사용한 방법인데요.
제가 딕셔너리를 만들어서 두 힙의 데이터를 동기화했던 방법과 달리 각 힙의 첫번째 요소를 비교해서 동기화해준 방법입니다.
이 방법이 제 방법보다 좀 더 코드가 간결하고 좋은 것 같아서 가져와봤습니다.
이상한 곳에서 계속 삽질하다가 …
=> [2021.09.08] 전진성 프로그래머스 이중우선순위큐(lv3), 디스크 컨트롤러(lv3)

JeongGod/programmers/stack&queue/disk_controller.py, JeongGod/programmers/stack&queue/two_prior_queue.py
<풀이>
1. 현재 jobs들을 요청이 들어온 순서대로 sort하고 queue로 만든다.
2. queue를 보고, 현재 시간(cur_time)이전에 요청이 들어온 것이 있다면 heapq에 넣습니다.
heapq는 처리하는데 가장 짧은 시간이 걸리는 것을 기준으로 했습니다.
3. heapq에서 하나를 해당 일을 처리합니다.
answer = (현재 시간 - 요청 시간)`일이 시작되는데 기다린 시간` + 실행 시간
cur_time = 현재 프로세스의 시간
한 리스트안에 두 개의 우선순위 큐를 생각하는데 힘들었네요.
max_hq, min_hq 둘 다 결국에는 전체 데이터를 나타내는 것이기에, pop한 개수에 따라서 리스트에 값이 남아있는지 없는지 판단할 수 있다고 생각했습니다.
<풀이>
1. 최대 힙과, 최소 힙 2가지를 사용하여 저장합니다.
2-1. **insert가 들어오면** 
두 개의 힙에 넣어줍니다.
2-2. **pop이 들어오면**
pop의 개수를 세어줍니다.
만약 배열의 모든 것을 pop한 것이라면 두 개의 배열을 초기화 한 후, pop의 개수도 초기화 합니다.
4. 마지막에 최대 힙과 최소 힙의 값을 출력합니다.
=> [2021.09.08] 이정규 Programmers 디스크 컨트롤러, 이중 우선순위 큐

JeongGod/programmers/kakao/biggest.py, JeongGod/programmers/kakao/menu.py
테케 1~6번인 틀려서 엄청 고생했네요.. 왜 틀리는지 아직도 이해가 안가서 일단 푸쉬해놓고 이해해보겠습니다.
제가 생각했던 방법은 원래 **맨 앞자리의 수**를 하나씩 더해가며 4자리를 만드는 것이였습니다.
[6, 10, 2] => [6666, 1011, 2222] 이렇게요.
그런데 이렇게 하면 틀리고 기존에 있던 숫자를 계속해서 붙여나가는 느낌으로
[6, 10, 2] => [6666, 1010, 2222] 이렇게 하면 맞더라구요. 뭔 차인지.. 아직 모르겠습니다.
<풀이>
1. 수를 비교하기 위해서 같은 자릿수로 만듭니다. 현재 문제에서 1000이 수의 최대라고 했으니 4자리로 만들어줍니다.
2. 그 뒤에, 4자리로 만든 숫자를 비교합니다. 만약에 같다면 만들기 전에 숫자가 더 큰 순으로 정렬합니다.
3. 정렬한 배열을 하나씩 붙여나갑니다.
구현 문제네요. 제 방식은 테케에서 2초정도 걸리는 케이스도 있습니다. 모든 경우의 조합을 다 구하다보니 그런 것 같아요.
만약에 밑에 Counter풀이처럼 해당 조합의 경우만 본다면 확실히 시간이 줄어듭니다.
Counter사용 풀이도 밑에 적어놓았습니다.
<풀이>
1. 손님이 시킨 메뉴의 조합을 모두 구합니다. 구한 조합을 모두 dict에 담습니다. (key = 조합, value = 해당 조합을 시킨 횟수)
2. (key, value)로 가져오는데 value값으로 sort를 진행합니다.
3. sort를 한 리스트들을 하나씩 흝으면서 담습니다.
담는 기준은 course에서 요구하는 조합의 길이와 맞고, 그 해당 조합을 시킨 횟수가 최대인지 확인하고 담습니다. …
=> [2021.09.09] 이정규 Programmers 가장 큰 수, 메뉴 리뉴얼

JYP/Programmers_test_kit/sort_max_number.py, JYP/kakao_blind/2021_menu_renewal.py
`설명`
- defaultdict를 이용하여 첫째 자리 숫자로 각각 다른 그룹을 지어주었어요.
- 그 다음 첫째 자리 숫자에 따라 정리된 그룹을 내림차순으로 sort했습니다. (예: [9, 91, 90], [7, 77, 733], ..., [1, 187] 순서)
- 그리고 각 그룹 내에서 sort를 다시 진행했습니다. 여기서 제일 헤맸는데요,
- 처음 생각했던 로직은 첫째 자리 숫자를 key로 하고 각 그룹의 최고 자리 숫자 길이(입력값이 1000이하라는 걸 잊고 있었어요)에 비교하여 보정한 뒤 각 값을 비교하는 거였습니다. 
- 예를 들면, 41과 412가 입력값이라면 결과는 41412가 되어야 하는데, 이를 위해 41을 414로 보정한 뒤 412와 비교해보려고 했습니다. 코드 구현이 잘 안되어서 이 부분은 결국 실패했어요. 
- 41을 414로 보정하는 로직은 가장 큰 수와의 자릿수 차이만큼 4(최고 자리 숫자)를 계속 붙여주는 방식이었어요.
`어려웠던 점`   
- 입력 조건을 제대로 보지 않아서 한참 고생했습니다^^;
- 최댓값이 1000밖에 되지 않는데 자릿수 보정에 대해서 오래 고민하고 있어서 시간을 많이 잡아먹었습니다. 조건을 꼼꼼히 따져봐야겠어요...
`알게된 점`
- 디스코드에서 다른 분들께서 말씀해주신덕분에 파이썬에서 문자열과 정수형의 대소 비교의 차이에 대해 이해할 수 있었습니다. 
<br>
<br>
`설명`   
- 빈도 수 체크를 위해 Counter객체를 사용했습니다. 
- 희지님께서 올려주신 리스트 컴프리헨션을 적용해보았습니다. 길게 썼던 코드가 한 줄로 줄어들고 나머지를 싹 …
=> [2021.09.09] 박지윤 - 프로그래머스 가장 큰 수, 메뉴 리뉴얼

limhizy15/two_pointer/pro_72412.py
- 일단 가능한 정보의 조합을 구하고 이걸 key, 해당 조합에 속하는 점수를 value로 해서 딕셔너리를 만들면 찾을 때 쉽겠다 생각했습니다. 근데 이제 query로 조건에 맞는 것을 셀 때 효율성에서 계속 시간 초과가 나더라구요.. 20분 머리 싸매다가 검색해보니 이진 탐색으로 해결해야한다는 걸 알았습니다. 근데 이진탐색을 어떻게 하는지 기억이 안나서 일단 따라쳤어요.. 😂
1. info의 원소를 4가지 정보 / 점수로 분리하고, 4가지 정보로 가능한 모든 조합을 구합니다. (0, 1, .., 4개를 고르는 경우의 수) 이 조합을 key로 하고 점수를 value list에 넣었습니다.
2. 후에 이진탐색하기 위해 value list를 정렬했습니다.
3. 쿼리도 info를 변경하는 것과 동일합니다. 다만 여기선 'and'와 '-'가 있기 때문에 이걸 replace 메서드로 없애주었어요.
4. 이제 3번에서 이쁘게 가공된 쿼리를 key로 하는 딕셔너리 원소가 존재하는지 확인합니다. 존재하지 않으면 0개이므로 0을 정답에 넣어줍니다. 
5. 존재하면 value들 중에서 찾고자하는 점수를 기준으로 이진탐색을 해서 인덱스를 찾아냅니다. 이제 그 이상인 점수를 구해야하니까 value의 원소 개수에서 인덱스를 빼면 타겟 점수 이상인 원소의 개수가 나옵니다. 
- bisect_left를 쓴 이유가 아마 타겟 점수가 없으면 그거 왼쪽에 있는 애를 리턴해서 그런 것 같아요.. 사실 아직 이진탐색을 잘 이해못해서 그런갑다한 상태이고 풀리하고 조금 더 찾아보려합니다
=> [2021.09.10] 임희지 programmers 순위 검색

notCoderJ/kakao/rank.py
풀이요약
bit 연산을 이용하기 위해 bit 테이블을 만들어서 이용했습니다.
1. 가능한 선택지에 대해 종류별로 1bit씩 할당해서 아래와 같이 자리값을 지정합니다.
언어는 최상위 3bit
직종은 다음 상위 2bit
경력은 그다음 상위 2bit
음식은 최하위 2bit
2. 주어진 info의 각 항목들을 해당 테이블을 이용해 값으로 치환해서 모두 더한 후
그 값을 ap_cnt의 인덱스로 하여 코딩 테스트 점수를 추가합니다.
3. 2에서 채워진 ap_cnt의 빈 값들을 모두 제거하고, (인덱스, 점수의 sorting 값) 형태로 변환합니다.
4. 주어진 query를 파싱해서 2번과 같이 table을 이용해 위치 값으로 치환한 후
해당 값과 ap_cnt의 인덱스를 and연산해서 query의 위치값과 동일한 경우
이진 탐색을 이용해 현재 query의 점수보다 큰 점수의 갯수를 구해 해당 answer자리에 더해줍니다.
어려웠던 점
처음에는 딕셔너리에다가 선택가능한 각 항목별로 info의 각 index를 리스트 형태로 넣어주고 query에서 일치하는 리스트들을 모두 가져와서 교집합을 구한 후 그 교집합의 인덱스로 점수를 만족시키는 애들을  찾아 구했습니다. 이렇게 하니 정확성은 모두 통과되는데 효율성이 0점이더라구요... 생각해보니 10만번 반복할 때 5만번씩 반복하면 터지겠다 생각했습니다.
그래서 비트연산이 떠올랐고 비트연산으로 로직을 갈아 엎었습니다. 하지만 요 방법도 속도는 많이 빨라졌지만 엣지케이스에서 위와 동일한 현상을 가져올 수 있더라구요. 그래서 한참 헤메다가 이진탐색이라는 힌트를 얻어서 통과할 수 있게 …
=> [2021.09.10] 전진성 프로그래머스 2021 카카오 블라인드 순위 검색(lv2)

JYP/kakao_blind/2021_rank_search_error_1.py, JYP/kakao_blind/2021_rank_search_error_2.py, JYP/kakao_blind/2021_rank_search_error_3.py, JYP/kakao_blind/2021_rank_search_error_4.py, JYP/kakao_blind/2021_rank_search_error_5.py, JYP/kakao_blind/2021_rank_search_error_6.py
이번엔 결국 못 풀었네요. ㅠㅠ
이진 탐색을 더 공부하고 빠른 시일 내에 다시 제대로 된 풀이를 업로드 해보겠습니다.
제대로 된 풀이를 못 올린 대신 에러케이스에 대한 분석을 올려봅니다.
- [노션 페이지 공유](https://freckle-alarm-005.notion.site/9efce2667be04c9caeccb03e73396d65) - 노션에도 우선 정리해 두었습니다.
- 시간은 최소, 최대 시간으로 표기했습니다.
- `0.17ms` `335.60ms`
- 이중for문을 돌아봤습니다. 제출하기 전부터 이미 통과가 안될 줄은 알고 있었지만요.ㅎㅎ
- 앗 이건 시간 캡쳐를 안했네요.
- 그런데 다시 돌려보니 아예 에러가 납니다. 코드를 기록하다가 어딘가를 실수해서 날린 거 같기도 하고요. 
- 중요한 내용은 없으니 패스!
- `0.09ms` `79.09ms`
- 아까보다 최대 시간이 훨씬 줄어서 통과할 수 있을 거라 기대했는데 실패했네요.ㅠㅠ
- 이중 for를 피하려면, 각 자료를 최소한의 조회가 발생하게 전처리 한 다음 비교 작업을 수행해보자고 생각했습니다.
- 하지만 찾아보니 문자열에 replace를 적용하면 시간초과가 발생한다고 합니다.
- 문자열 전처리에 드는 시간도 최소화하려고 문자와 숫자 부분을 분리해서 문자 부분을 set으로 처리해서 쿼리와 지원자 데이터 스펙을 비교했습니다.
- replace 함수를 버렸더니 빨라지긴 했는데 여전히 시간초과네요. 이게 핵심이 아닌가봅니다.
- `0.14ms` `78.79ms`
- 혹시 split도 버리면 통과하려나 기대를 했는데, 역시 실패했습니다. 
- …
=> [2021.09.10] 박지윤 프로그래머스 검색순위(에러케이스)

JeongGod/programmers/binary_search/immigration.py, JeongGod/programmers/kakao/candidate_key.py
"이분 탐색"이라는 키워드에 꽃혀서 뭔가 바로 풀이가 떠오르긴 했네요. 실전에서는 바로 떠오를 수 있을지는 모르겠네요ㅠㅠ
마지막에 자꾸 테스트케이스 4~5개정도가 틀리길래 왜그런가 봤더니 `n * max(times)`를 안하고 10억으로 잡고해서 삽질 좀 했네요.
<풀이>
1. left : 제일 최소로 걸리는 시간, right : 최고로 많이 걸리는 시간
2. 이분 탐색을 이용해 mid(시간)일 경우에 현재 심사위원들이 몇 명을 처리할 수 있는지 판단합니다.
심사위원이 mid인 시간에 처리할 수 있는 최대 인원 = mid // 심사위원이 1명 처리하는데 걸리는 시간
3. 만약 그 인원이 현재 n명보다 많다면 mid를 작은 곳에서 탐색합니다. 반대는 mid를 큰 값에서 탐색합니다.
4. 이분탐색이 끝나면 left값을 return합니다.
처음에 조합으로 먼저 풀고, 진성님이 전에 푸셨던 비트마스크로 풀 수 있어보여서 다른 사람 풀이를 참조해서 풀어봤습니다.
아직 비트마스크가 익숙치 않아서 쓰기 힘들더라구요.. 그래도 코테에서 자주 등장하는 유형같아보이니 열심히 연습해야겠습니다.
<조합 풀이>
모든 조합을 다 둘러보는 것으로 풀이를 했습니다.
1. dfs를 이용하여 모든 조합을 다 둘러봅니다.
- 유일성 판단
1. 해당 index끼리 튜플로 묶어 집합으로 저장하여 유일성을 확인했습니다.
- 최소성 체크
1. 후보키들을 집합으로 저장했습니다. 
2. 후보키와 합집합을 했을시에 길이가 그대로라면 해당 키는 후보키를 갖고 있는 것으로 판단하여 최소성을 체크합니다.
<비트마스크 풀이>
위와 로직은 똑같습니다. 모든 조합 …
=> [2021.09.14] 이정규 Programmers 입국심사, 후보키

notCoderJ/binary_search/immigration.py, notCoderJ/kakao/candidate_key.py
이 문제는 그림을 그려놓고 생각해보니 방향성을 좀 더 쉽게 잡을 수 있어서 어렵지 않게 풀었습니다.
풀이 요약
1. 모든 사람이 검사를 마친 최대 시간을 구합니다. == 최대 심사 시간 * (입국자 / 심사자)
2. 이분 탐색을 수행하며 매번 처리 시간을 반토막내고, 해당 시간에 각 심사원들이 처리한 입국자 수를 구해 합하고
그 수와 총 입국자의 수를 비교합니다.
2-1. 만약 같거나 넘는다면 answer값을 현재 중앙값으로 갱신하고 중앙값의 좌측에 대해 2번 과정을 재수행합니다.
2-2. 만약 작다면 중앙값의 우측에 대해 2번 과정을 재수행합니다.
어려웠던 점
처음에는 간단하게 생각하고 combinations를 이용해서 컬럼의 인덱스에 대한 모든 조합을 구한 후 후보키가 발생하는지 확인하였습니다. 만약 후보키가 발생하면 그 후보키를 만든 인덱스를 제거해주면서 다음 컬럼의 인덱스 조합을 구할 때 해당 인덱스가 포함되지 않게 하였습니다. 이렇게 했더니 테스트 케이스에서 5개정도? 계속 실패하더라구요. 도통 원인을 못찾겠어서 질문 게시판을 좀 찾아보니 최소성과 관련된 부분이라는 글을 보고 곰곰히 생각해봤습니다. 생각하다 보니 이렇게하면 제외한 키로 만들 수 있는 조합을 배제해버리게 된다는 걸 꺠달았습니다. 그래서 어떻게 할까 고민을 하다가 잠깐 생각해봤던 비트마스크를 이용해보기로 마음먹고 코드를 갈아엎으니 통과할 수 있었습니다.
풀이 요약
bitmask를 이용해서 풀었습니다.
bitmask 문제 풀이가 어떤 방식인지 제대로 풀어본적이 없어서 이런식으로 쓰는게 맞나 싶네요...
1. 먼저 컬럼의 모든 조합의 …
=> [2021.09.14] 전진성 프로그래머스 입국심사(lv3)

JYP/Programmers_test_kit/enter.py, JYP/kakao_blind/2019_key.py
- 후보키는 마지막에 최소성에서 계속 걸리고 있어서 내일 좀 더 연구한 다음에 올려보겠습니다 🙏
- 아직 머지가 안됐네요, 업데이트 했습니다!
- bisect를 한 번 써보려고 했는데 결국 못쓰고 일반적인(?) while문으로 해결했습니다.
- 인터넷도 많이 참고했고요; 
`로직`
- 어떤 값을 탐색할 것인가? 여기서 좀 헤맸어요. 사람 수? 입력값 times그 자체? 
- 답은 최소시간부터 최대시간, 시간 그 자체를 두고 탐색해야 하는 거였더라구요.;
- 이진 탐색시 탐색 대상을 잘 찾아야겠어요.
- 검색대에서 각각 time만큼의 시간을 쓴다면 한 검색대마다 사용할 수 있는 시간(mid)동안 mid//time 만큼의 인원을 처리할 수 있습니다.
- 그 mid//time값의 합을 모두 모으면 전체 검색대에서 사용할 수 있는 시간 동안 처리할 수 있는 인원의 총합이 됩니다(cnt)
- 인원 총합이 문제에서 준 n보다 작으면 탐색구간을 오른쪽(*mid보다 긴 시간)으로 옮기고(start = mid+1)
- 인원 총합이 문제에서 준 n보다 크거나 같으면 탐색구간을 왼쪽(*mid보다 더 짧은 시간)으로 옮깁니다.
- 시작 구간이 종료 구간과 같거나 넘어갈 때 while문이 종료되고 그때의 시작시간이 최솟값이라서 이를 답으로 반환합니다.
- (마지막 줄 제가 이해가 부족한지 말로 설명하고 나니 좀 이상한데, 보시고 아니다 싶으면 댓글 부탁드립니다 🙇‍♀️)
`알게된 점`
- 이진탐색의 기본은 정렬된 값을 돈다는 것, 그리고 시간복잡도가 로그스케일로 줄어들 수 있다는 점은 이번 코드 풀어보면서 이해가 되었습니다. …
=> [2021.09.14] 박지윤 프로그래머스 - 입국심사, 카카오 - 후보키

limhizy15/implementation/pro_17683.py
- 문제 읽는 데 시간이 좀 오래걸렸고 구현하는데도 부분부분 어떻게 해야될지 잘 모르겠어서 오늘은 검색을 좀 많이 했습니다. 문제를 해석하는 능력이 늘질 않는 것 같아요 !!!!! 😤일단 아래와 같이 풀었습니다.
1. 사용되는 음에는 '#'이 붙은 친구들이 있는데 처리하기 까다로우므로 소문자로 치환해줍니다. 'A#' => 'a' 
2. 곡정보들을 빙글빙글 돌면서 재생시간(끝난 시각 - 시작 시각), 제목, 음을 봅니다. 이 때, 음은 1번과 같이 치환하는 과정을 거칩니다. 그리고 이제 음을 보고 실제로 재생된 음들의 모음을 얻어야하니까 음 * 재생시간으로 늘려주고 (반복재생이므로) 인덱스 슬라이싱을 해줍니다! 
3. 위에서 얻은 실제 재생된 음이 네오가 들은 음을 포함하는지 확인합니다. 그리고 기존에 answer과 비교해서 재생시간이 더 크면 answer를 바꿔줍니다~
=> [2021.09.17] 임희지 programmers 방금그곡

notCoderJ/greedy/life_boat.py
풀이요약
보트에는 최대 2명씩만 태울 수 있기 때문에 사람들의 몸무게를 정렬하여
현재 남은 사람들 중 가장 무거운 사람과 가장 가벼운 사람을 계속 짝지으며 보트에 태우는 방법으로 풀이했습니다.
테스트 문제는 통과했는데, 제출 시 실패해서 못 올렸습니다. 지금 생각할 여를이 없어서... 사건이 좀 해결되는대로 다시 풀어보겠습니다.
=> [2021.10.21] 전진성 프로그래머스 구명보트

JeongGod/programmers/binary_search/bridge.py, JeongGod/programmers/kakao/cache.py
흐미.. 생각하기가 어려워서 풀이를 참조했슴다..
생각하기가 어려워서 그렇지 이분탐색이라는 것만 알면 풀이법은 다 비슷비슷하네요.
시간복잡도는 이분탐색을 이용하기에 (log10억(가능한 거리) * 50000(전체 돌의 개수)) 이기에 충분히 가능합니다. 역시 로그가 짱입니다.
<풀이>
1. distance의 최소, 최대를 잡는다. 이제 가능한 거리를 이분탐색을 이용해 가정한다.
mid = (최소 + 최대) // 2
2. 만약 가정한 답(mid)을 기준으로 했을 경우 삭제해야하는 돌의 개수가 n보다 작거나 같다면
1. 이건 가능한 경우다.
하지만, 지금 가정한 답(mid)보다 더 크게 만들 수 있을 수도 있다.
3. 만약 가정한 답(mid)을 기준으로 했을 경우 삭제해야하는 돌의 개수가 n보다 크다면
1. n개를 삭제해도 mid보다 길이를 늘릴 수 없다는 얘기이므로 우리가 가정한 답(mid)는 불가능하다.
그렇기 때문에 mid값을 줄여본다.
처음에는 dict형식으로 풀었는데 다른 사람의 풀이를 보고 큐로 푸는게 맞다.. 싶었습니다.
그래서 2가지로 풀었습니다.
<풀이>
1. Miss일 경우
1. 오랫동안 캐시에 남아있는 친구를 찾습니다. cities를 돌 때 마다 캐시에 들어있는 얘들에게 +1을 해주어 가장 큰 값이 제일 오랫동안 남아있는 친구이므로 삭제하고 dict에 넣습니다.
2. Hit일 경우
1. 해당 친구는 캐시에서 쓰였으니 0으로 초기화하여 가장 나중에 빠지게 설정합니다.
=> [2021.11.01] 이정규 Programmers 징검다리, 캐시

notCoderJ/binary_search/stepping_stone.py, notCoderJ/kakao/cache.py
이분탐색은 어떻게 적용해야할지 감이 안오네요... 구글님의 힘을 빌렸습니다. 그래도 아직 제대로 이해 못했어요😭
바위를 뺸 수(cnt)랑 n이랑 같을 때만 answer 값을 갱신해줘야할 것 같은데 cnt < n인 경우에도 갱신해주지 않으면 실패하네요. 다시 천천히 봐야겠습니다.😤
풀이요약
1. 0부터 최대 가능한 거리 distance까지 이분 탐색을 반복 수행하며, 중간 값을 가능한 최대 거리라 가정합니다.
2. 중간 값보다 간격이 적은 바위들을 하나씩 제거하며 제거한 바위 수가 n과 동일할 경우 answer를 중간값으로 변경해줍니다.
딕셔너리를 이용해서 LRU 캐시를 구현해보려고 했지만 잘 되지 않아서 비효율적이지만 리스트를 이용해서 풀이했습니다.
오랫만에 알고리즘을 풀려니 머리가 안돌아가네요ㅠ
풀이요약
리스트를 이용해 LRU 알고리즘으로 동작하는 캐시를 구현하여 풀이했습니다.
각 도시들을 순회하며 캐시에 hit되는 경우 answer +1을 해주고 캐시에서 해당 도시를 꺼내 맨 끝으로 넣어줍니다.
캐시에 없는 경우 answer +5를 하고, 캐시의 현재 크기에 따라 해당 도시를 캐시에 넣거나 가장 오래된 도시를 꺼낸 후 캐시에 넣어줍니다.
=> [2021.11.01] 전진성 프로그래머스 징검다리(lv4), 2018 카카오 블라인드 1차 캐시(lv2)
